In [1]:
import pandas as pd
import numpy as np
from tqdm import tqdm
from os.path import join, dirname
import os
import histogwas.emb_gwas as eg
import glob

# Table 1

In [4]:
tissue_list_cluster = {
    'Skin_Sun_Exposed_Lower_leg': [0, 1, 2, 3, 4, 5, 7],
 'Esophagus_Muscularis': [0, 1, 2, 3, 4, 5, 6, 7, 8],
 'Stomach': [0, 2, 4, 5, 7, 10],
 'Nerve_Tibial': [0, 6],
 'Colon_Transverse': [0, 1, 2, 3, 5, 6, 7, 8],
 'Esophagus_Mucosa': [0, 1, 2, 3, 4, 7, 8],
 'Artery_Tibial': [0, 2, 4, 5],
 'Breast_Mammary_Tissue': [0, 1, 8],
 'Adipose_Subcutaneous': [0, 1, 2, 3, 4, 5, 6, 7, 8],
 'Muscle_Skeletal': [1, 2, 3, 4, 5, 7],
 'Thyroid': [0, 1, 2, 3, 4, 5, 6]}

In [5]:
tissue_colors = {
    'Esophagus_Muscularis': 'lightseagreen',
    'Esophagus_Mucosa': 'mediumaquamarine',
    'Colon_Transverse': 'lightpink',
    'Stomach': 'palevioletred',
    'Skin_Sun_Exposed_Lower_leg': '#D8BFD8',
    'Breast_Mammary_Tissue': 'rosybrown',
    'Thyroid': '#FFDAB9',
    'Adipose_Subcutaneous': '#ADD8E6',
    'Muscle_Skeletal': 'lightsalmon',
    'Artery_Tibial': 'darkorange',
    'Nerve_Tibial': 'orangered',
}

In [6]:
cluster_count = 0
for tissue in tissue_list_cluster.keys():
    cluster_count +=  len(tissue_list_cluster[tissue])

In [7]:
print(f"Total cluster count {cluster_count}")

Total cluster count 68

# snp to gene prediction

In [8]:
from utils import get_snp, get_expression, get_egenes, merge_dfs
from mtgwas import GWAS
from limix_core.util.preprocess import gaussianize
from statsmodels.stats.multitest import multipletests
import gseapy as gp
from mygene import MyGeneInfo

In [9]:
from histogwas.emb_gwas.utils import df_match

In [10]:
def merge_dfs(df1, df2, key1=None, key2=None, left_index=False, right_index=False):


    if key2 is None:
        key2 = key1

    # df1 indexing
    if left_index:
        _df1 = pd.DataFrame({'x': df1.index.values})
    else:
        _df1 = pd.DataFrame({'x': df1[key1]})
    _df1['idx1'] = np.arange(len(_df1))

    # df2 indexing
    if right_index:
        _df2 = pd.DataFrame({'x': df2.index.values})
    else:
        _df2 = pd.DataFrame({'x': df2[key2]})
    _df2['idx2'] = np.arange(len(_df2))

    # match
    _dfm = _df1.merge(_df2, how='inner', on='x')
    idx1 = _dfm['idx1'].values
    idx2 = _dfm['idx2'].values

    return idx1, idx2

def load_covs(covfile):
    dfcov0 = pd.read_csv(covfile, sep='\t').dropna()
    dfcov = pd.get_dummies(dfcov0['DTHHRDY'].astype(int).astype(str))
    dfcov['SEX'] = 1 * (dfcov0['SEX'].values==2)
    dfcov['AGE'] = dfcov0['AGE'].str.split('-').str.get(0).astype(int) + 5
    dfcov['SID'] = dfcov0['SUBJID']
    dfcov = dfcov.set_index('SID')
    return dfcov

In [11]:
# Here I am reading the bed file and creating its anndata
pcfile='/lustre/groups/casale/datasets/gtex/wgs/GTEx_Analysis_2017-06-05_v8_WholeGenomeSeq_838Indiv_Analysis_Freeze.SHAPEIT2_phased.MAF01.pca.eigenvec'
bfile='/lustre/groups/casale/datasets/gtex/wgs/GTEx_Analysis_2017-06-05_v8_WholeGenomeSeq_838Indiv_Analysis_Freeze.SHAPEIT2_phased.MAF02'

# read bfile and pcs
num_pcs = 4
gdata = eg.read_plink(bfile, pcfile, num_pcs=num_pcs)

# read covs
covfile = '/lustre/groups/casale/datasets/gtex/phenotypes/GTEx_Analysis_v8_Annotations_SubjectPhenotypesDS.txt'
dfcov = load_covs(covfile)

Mapping files: 100%|██████████| 3/3 [00:13<00:00,  4.63s/it]

In [13]:
# Reading the hits
outdir = '/lustre/groups/casale/code/users/shubham.chaudhary/output/projects/gtex/pysrc_v2/preprocessing/supplementary/SupplementaryTable_3'
outfile = join(outdir, 'hits.csv')
df_hits = pd.read_csv(outfile,)

In [14]:
def get_covs(gdata, dfcov):

    # read covs
    covfile = '/lustre/groups/casale/datasets/gtex/phenotypes/GTEx_Analysis_v8_Annotations_SubjectPhenotypesDS.txt'
    dfcov = load_covs(covfile)


    dfpc = (gdata.obs - gdata.obs.mean(0)) / gdata.obs.std(0)
    idx1, idx2 = merge_dfs(dfpc, dfcov, left_index=True, right_index=True)
    dfpc = dfpc.iloc[idx1]
    dfcov = dfcov.iloc[idx2]
#     dfcov[['AGE', 'SEX',]]
    dfcovall = pd.concat([dfpc.iloc[:,:4], dfcov[['AGE', 'SEX',]]], axis=1)
    
    
    return dfcovall

In [15]:
df_hits

,Unnamed: 0,snp,chrom,pos,a0,a1,maf,p_value,cluster_i,tissue,color
0,213910,chr1_78663229_G_A_b38,1,78663229,G,A,0.571043,1.638075e-09,4,Esophagus Mucosa,mediumaquamarine
1,213922,chr1_78667706_T_A_b38,1,78667706,T,A,0.571043,1.638075e-09,4,Esophagus Mucosa,mediumaquamarine
2,3020994,chr5_174255970_A_G_b38,5,174255970,G,A,0.856115,3.936964e-10,3,Skin Sun Exposed Lower leg,#D8BFD8
3,4778910,chr9_97771865_A_G_b38,9,97771865,A,G,0.629496,2.047532e-10,4,Thyroid,#FFDAB9
4,4778911,chr9_97772541_A_T_b38,9,97772541,A,T,0.629496,2.047532e-10,4,Thyroid,#FFDAB9
...,...,...,...,...,...,...,...,...,...,...,...
64,4966601,chr10_17381399_G_A_b38,10,17381399,A,G,0.754496,1.386340e-09,2,Adipose Subcutaneous,#ADD8E6
65,4966602,chr10_17381408_T_C_b38,10,17381408,C,T,0.754496,1.386340e-09,2,Adipose Subcutaneous,#ADD8E6
66,4966607,chr10_17381887_G_A_b38,10,17381887,A,G,0.754496,1.386340e-09,2,Adipose Subcutaneous,#ADD8E6
67,4966608,chr10_17382105_G_A_b38,10,17382105,A,G,0.754496,1.386340e-09,2,Adipose Subcutaneous,#ADD8E6
68,4966627,chr10_17384475_A_C_b38,10,17384475,C,A,0.758993,7.387893e-10,2,Adipose Subcutaneous,#ADD8E6

In [18]:
path_all = '/lustre/groups/casale/code/users/shubham.chaudhary/output/projects/gtex/pysrc_v2/preprocessing/stage6/hgwas/retccl/all_tissue_FWER_corrected.csv'
fwer20 = 3.232995e-09
df_all = pd.read_csv(path_all, sep='\t')
df_all = df_all[df_all['p_value']<fwer20]
df_all = df_all.drop(columns = ['Unnamed: 0.1', 'Unnamed: 0'])

chr9_97772921_C_G_b38 2 Thyroid 'rs7030256' <br>
chr5_174255970_A_G_b38 2 Skin_Sun_Exposed_Lower_leg 'rs1432621' <br>
chr1_78663229_G_A_b38 7 Esophagus_Mucosa 'rs3766325' <br>
chr10_17384475_A_C_b38 1 Adipose_Subcutaneous 'rs2770197' <br>

In [20]:
snp_to_snpid = {'chr9_97772921_C_G_b38': 'rs7030256',
'chr5_174255970_A_G_b38' : 'rs1432621',
'chr1_78663229_G_A_b38' : 'rs3766325',
'chr10_17384475_A_C_b38': 'rs2770197'}

In [21]:
def get_enrichment(df_regulated, dfgene, top=50, type_='FDR'):
    print(f"Doing for top {top} gene")
    
    gene_list = df_regulated['gene_name'].to_list()
    if top != 'all':
        gene_list = gene_list[:top]

    background = dfgene.columns.values.astype(str).tolist()
    # Perform pathway enrichment analysis
    enr_bg = gp.enrichr(gene_list=gene_list, gene_sets=['MSigDB_Hallmark_2020'], organism= 'human', background=background, outdir=None)
    
    return enr_bg.results

In [22]:
# load expression data
def get_id_gene_map(tissue):
    import gzip
    file_path = f'/lustre/groups/casale/code/users/shubham.chaudhary/output/projects/gtex/pysrc_v2/emb-gwas/tpm_gene/gene_tpm_2017-06-05_v8_{tissue.lower()}.gct.gz'
    with gzip.open(file_path, 'rt') as f:
        # Read the GCT file into a pandas DataFrame
        data = pd.read_csv(f, skiprows=2, delimiter='\t')
    
    id_gene_map = dict(zip(data['Name'],data['Description']))
    return id_gene_map

In [23]:
def get_expression_normalized(tissue):
    expr_path = f"/lustre/groups/casale/datasets/gtex/phenotypes/GTEx_Analysis_v8_eQTL_expression_matrices/{tissue}.v8.normalized_expression.bed.gz"
    seed = 0
    dfe = pd.read_csv(expr_path, sep="\t", index_col=3)
    dfe = dfe[dfe['#chr'].str.split('chr').str[-1].isin(np.arange(23).astype(str))]
    dfe = dfe.iloc[:,3:].T
    return dfe

In [24]:
id_gene_map = get_id_gene_map(tissue)
dfgene = get_expression_normalized(tissue)
dfgene.columns = dfgene.columns.map(id_gene_map)

In [ ]:
# Here we are doing association of lead variant(in each signal) with gene expression
import warnings
warnings.filterwarnings('ignore')

association_type = [
    'withCovariate', 
                    # 'withoutcovariates'
                   ]
for type_ in association_type:

    outdir = f'/lustre/groups/casale/code/users/shubham.chaudhary/output/projects/gtex/pysrc_v2/preprocessing/supplementary/SupplementaryTable_3_version7/{type_}'
    os.makedirs(outdir, exist_ok=True)


    correction_type = [
                        # 'FDR', 
                       'Bonferroni'
                      ]
    
    for test_correction_type in correction_type:
        result_all_tissue = []
        for tissue in df_all['tissue'].unique():
           


            _ = df_all[df_all['tissue']==tissue]
            chroms = _['chrom'].unique()
            result_tissue= []
            for chrom in chroms:
                temp_ = _[_['chrom']==chrom]
                temp_ = temp_.sort_values(by=['p_value'])
                snp = temp_.iloc[0]['snp']
                maf = temp_.iloc[0]['maf']
                snp_p_value = temp_.iloc[0]['p_value']
                cluster_i = temp_.iloc[0]['cluster_i']



                snp_id = snp
                tissue = tissue
                dfcovall = get_covs(gdata, dfcov)

                # print(f"Before nan removal {len(dfcovall)}")
                dfcovall = dfcovall.dropna()


                snp_df = get_snp(snp_id, gdata)

                dfgene = get_expression(tissue)
                idx1, idx2, idx3 = df_match([dfgene, snp_df, dfcovall])
                dfgene = dfgene.iloc[idx1]
                snp_df = snp_df.iloc[idx2]
                dfcovall = dfcovall.iloc[idx3]
                covariates = np.concatenate([dfcovall.values, np.ones((dfcovall.values.shape[0], 1))], axis=1)

                # covariates = dfcovall.values
                # print(f"After nan removal {len(dfcovall)}")

                df_result = pd.DataFrame(columns = ['p_value'], index=dfgene.columns)

                dfgene  = gaussianize(dfgene.values)
                Y = dfgene
                if type_ == 'withCovariate':
                    gwas = GWAS(np.array(snp_df))
                    gwas = GWAS(Y, F=covariates)
                else:
                    gwas = GWAS(Y)
                # Here I am gaussianizing the expression
                # U = svd(dfgene.values, full_matrices=False)[0]
                # gwas.process(dfgene) 
                gwas.process(np.array(snp_df)) 
                df_result['p_value'] = gwas.getPv().ravel()
                df_result['tissue'] = tissue
                df_result['snp_id'] = snp_id
                df_result['beta'] = gwas.getBetaSNP().ravel()
                df_result['qv'] = multipletests(df_result['p_value'], method='fdr_bh')[1]
                df_result['maf'] = maf
                df_result['cluster_i'] = cluster_i
                df_result = df_result.sort_values(by=['p_value'])
                temp = df_result


                # if test_correction_type == 'fdr':
                #     threshold = 0.05
                #     temp = df_result[df_result['qv']<(threshold)]
                # else:
                #     threshold = (0.05/len(df_result))
                #     temp = df_result[df_result['p_value']<(threshold)]

                if len(temp) >0:
                    _egene = get_egenes(temp['tissue'][0])
                    _egene = _egene[_egene['gene_name'].isin(temp.index.values)][['gene_name', 'gene_chr', 'gene_start', 'gene_end']].set_index('gene_name')
                    idx_l, idx_r = merge_dfs(temp, _egene, left_index=True, right_index=True)
                    temp = temp.iloc[idx_l]
                    _egene = _egene.iloc[idx_r]
                    temp[['gene_chr', 'gene_start', 'gene_end']] = _egene[['gene_chr', 'gene_start', 'gene_end']]

                    result_tissue.append(temp)
            if len(result_tissue)>0:
                print(tissue)
                tissue_snp_to_expr = pd.concat(result_tissue, axis=0)
                tissue_snp_to_expr = tissue_snp_to_expr.sort_values(by=['p_value'])
                if test_correction_type == 'FDR':
                    outfile = join(outdir, 'snpTogeneFDR', f'Topsnp_to_gene_expr_{tissue}.csv')
                else:
                    outfile = join(outdir, 'snpTogeneBonferroni', f'Topsnp_to_gene_expr_{tissue}.csv')
                os.makedirs(dirname(outfile), exist_ok=True)
                tissue_snp_to_expr.to_csv(outfile, sep='\t', index=True)
                result_all_tissue.append(tissue_snp_to_expr)


        # Reading snpTogene
        top_gene_count_to_consider = [50,
                                      # 100, 150, 200
                                     ]
        outfile = join(outdir, f'snpTogene{test_correction_type}', f'Topsnp_to_gene_expr_*.csv')
        for file in glob.glob(outfile):
            for top_gene_count in top_gene_count_to_consider:
                tissue = file.split('/')[-1].split('expr_')[1].split('.csv')[0]
                df_hits = df_all[df_all['tissue'] == tissue]
                print(tissue)
                df_tissue = pd.read_csv(file, sep='\t')
                df_tissue = df_tissue.sort_values(by=['p_value'])
                dfgene = get_expression(tissue)
                df_tissue.rename(columns={'Unnamed: 0': 'gene_name'}, inplace=True)
                df_upregulated = df_tissue[df_tissue['beta'] > 0]
                df_downregulated = df_tissue[df_tissue['beta']<=0]

                print(f"For {tissue} top {top_gene_count} correction type = {test_correction_type}")
                # pathway_upregulated = get_enrichment(df_upregulated, dfgene, top=top_gene_count,type_=test_correction_type)
                # pathway_downregulated = get_enrichment(df_downregulated, dfgene, top=top_gene_count,type_=test_correction_type)
                if len(df_upregulated) >0:

                    pathway_upregulated = get_enrichment(df_upregulated, dfgene, top = top_gene_count, type_=test_correction_type)
                    display(df_upregulated.head())
                    display(pathway_upregulated.head())
                if len(df_downregulated) >0:
                    pathway_downregulated = get_enrichment(df_downregulated, dfgene, top = top_gene_count, type_=test_correction_type)
                    display(df_downregulated.head())

                    display(pathway_downregulated.head())
                # Create an ExcelWriter object
                out_temp = join(outdir, f'{tissue}_{test_correction_type}_output_top_{top_gene_count}_geneConsidered.xlsx')
                with pd.ExcelWriter(out_temp) as writer:
                    # Write each DataFrame to a separate sheet
                    df_hits.to_excel(writer, sheet_name='hits', index=False)
                    df_tissue.to_excel(writer, sheet_name='snp_to_gene', index=False)
                    if len(df_upregulated) >0:
                        pathway_upregulated.to_excel(writer, sheet_name='upregulated', index=False)
                    if len(df_downregulated) >0:
                        pathway_downregulated.to_excel(writer, sheet_name='downregulated', index=False)

Thyroid
Spleen
Skin_Sun_Exposed_Lower_leg
Esophagus_Mucosa
Adipose_Subcutaneous
Thyroid
For Thyroid top 50 correction type = FDR
Doing for top 50 gene

,gene_name,p_value,tissue,snp_id,beta,qv,maf,cluster_i,gene_chr,gene_start,gene_end
1,CENPJ,8.820354e-31,Thyroid,chr9_97772921_C_G_b38,0.693229,1.868592e-27,0.668831,2,chr13,24882284,24922889
4,TPTE2P1,1.870313e-27,Thyroid,chr9_97772921_C_G_b38,0.654771,1.584903e-24,0.668831,2,chr13,24924677,24968487
6,CPAMD8,1.325091e-19,Thyroid,chr9_97772921_C_G_b38,0.511589,8.020586e-17,0.668831,2,chr19,16892947,17026815
7,DTX4,3.129176e-19,Thyroid,chr9_97772921_C_G_b38,0.543535,1.657290e-16,0.668831,2,chr11,59171430,59208509
10,RP11-756A22.7,5.134648e-18,Thyroid,chr9_97772921_C_G_b38,0.533252,1.977773e-15,0.668831,2,chr13,24933006,24936796

,Gene_set,Term,P-value,Adjusted P-value,Old P-value,Old adjusted P-value,Odds Ratio,Combined Score,Genes
0,MSigDB_Hallmark_2020,Hedgehog Signaling,0.008395,0.124047,0,0,17.358333,82.974162,CELSR1;NKX6-1
1,MSigDB_Hallmark_2020,Pancreas Beta Cells,0.013058,0.124047,0,0,13.342949,57.886840,NKX6-1;FOXA2
2,MSigDB_Hallmark_2020,Bile Acid Metabolism,0.039897,0.252680,0,0,6.918333,22.287129,SULT2B1;HSD17B6
3,MSigDB_Hallmark_2020,Estrogen Response Early,0.054382,0.258316,0,0,3.744073,10.901684,SULT2B1;MUC1;CELSR1
4,MSigDB_Hallmark_2020,Myc Targets V2,0.090896,0.345404,0,0,12.154519,29.147031,SLC19A1

Doing for top 50 gene

,gene_name,p_value,tissue,snp_id,beta,qv,maf,cluster_i,gene_chr,gene_start,gene_end
0,FAM163A,4.537380e-31,Thyroid,chr9_97772921_C_G_b38,-0.694002,1.868592e-27,0.668831,2,chr1,179743163,179816183
2,IGHE,1.957715e-30,Thyroid,chr9_97772921_C_G_b38,-0.650482,2.764947e-27,0.668831,2,chr14,105599941,105601728
3,FAM189A1,6.623082e-28,Thyroid,chr9_97772921_C_G_b38,-0.665878,7.015500e-25,0.668831,2,chr15,29120254,29570723
5,PLA2G4F,4.443909e-21,Thyroid,chr9_97772921_C_G_b38,-0.577363,3.138141e-18,0.668831,2,chr15,42139034,42156636
8,HK2,8.583262e-19,Thyroid,chr9_97772921_C_G_b38,-0.541636,4.040809e-16,0.668831,2,chr2,74833988,74893359

,Gene_set,Term,P-value,Adjusted P-value,Old P-value,Old adjusted P-value,Odds Ratio,Combined Score,Genes
0,MSigDB_Hallmark_2020,Myc Targets V2,0.090896,0.742396,0,0,12.154519,29.147031,HK2
1,MSigDB_Hallmark_2020,Myogenesis,0.131940,0.742396,0,0,2.499182,5.061855,ACHE;NCAM1;PVALB
2,MSigDB_Hallmark_2020,Hedgehog Signaling,0.133256,0.742396,0,0,7.727273,15.574182,ACHE
3,MSigDB_Hallmark_2020,Apical Surface,0.183494,0.742396,0,0,5.306122,8.996920,MAL
4,MSigDB_Hallmark_2020,Pperoxisome,0.212255,0.742396,0,0,4.465091,6.920744,DIO1

Thyroid
For Thyroid top 100 correction type = FDR
Doing for top 100 gene

,gene_name,p_value,tissue,snp_id,beta,qv,maf,cluster_i,gene_chr,gene_start,gene_end
1,CENPJ,8.820354e-31,Thyroid,chr9_97772921_C_G_b38,0.693229,1.868592e-27,0.668831,2,chr13,24882284,24922889
4,TPTE2P1,1.870313e-27,Thyroid,chr9_97772921_C_G_b38,0.654771,1.584903e-24,0.668831,2,chr13,24924677,24968487
6,CPAMD8,1.325091e-19,Thyroid,chr9_97772921_C_G_b38,0.511589,8.020586e-17,0.668831,2,chr19,16892947,17026815
7,DTX4,3.129176e-19,Thyroid,chr9_97772921_C_G_b38,0.543535,1.657290e-16,0.668831,2,chr11,59171430,59208509
10,RP11-756A22.7,5.134648e-18,Thyroid,chr9_97772921_C_G_b38,0.533252,1.977773e-15,0.668831,2,chr13,24933006,24936796

,Gene_set,Term,P-value,Adjusted P-value,Old P-value,Old adjusted P-value,Odds Ratio,Combined Score,Genes
0,MSigDB_Hallmark_2020,Pancreas Beta Cells,0.004757,0.118923,0,0,10.603093,56.706983,PCSK2;NKX6-1;FOXA2
1,MSigDB_Hallmark_2020,Estrogen Response Early,0.028344,0.261274,0,0,3.140867,11.191965,SULT2B1;MUC1;MLPH;RHOBTB3;CELSR1
2,MSigDB_Hallmark_2020,Hedgehog Signaling,0.031353,0.261274,0,0,8.400000,29.084583,CELSR1;NKX6-1
3,MSigDB_Hallmark_2020,Estrogen Response Late,0.115982,0.664791,0,0,2.250556,4.848412,SULT2B1;ISG20;MDK;TNNC1
4,MSigDB_Hallmark_2020,Bile Acid Metabolism,0.132958,0.664791,0,0,3.347755,6.754835,SULT2B1;HSD17B6

Doing for top 100 gene

,gene_name,p_value,tissue,snp_id,beta,qv,maf,cluster_i,gene_chr,gene_start,gene_end
0,FAM163A,4.537380e-31,Thyroid,chr9_97772921_C_G_b38,-0.694002,1.868592e-27,0.668831,2,chr1,179743163,179816183
2,IGHE,1.957715e-30,Thyroid,chr9_97772921_C_G_b38,-0.650482,2.764947e-27,0.668831,2,chr14,105599941,105601728
3,FAM189A1,6.623082e-28,Thyroid,chr9_97772921_C_G_b38,-0.665878,7.015500e-25,0.668831,2,chr15,29120254,29570723
5,PLA2G4F,4.443909e-21,Thyroid,chr9_97772921_C_G_b38,-0.577363,3.138141e-18,0.668831,2,chr15,42139034,42156636
8,HK2,8.583262e-19,Thyroid,chr9_97772921_C_G_b38,-0.541636,4.040809e-16,0.668831,2,chr2,74833988,74893359

,Gene_set,Term,P-value,Adjusted P-value,Old P-value,Old adjusted P-value,Odds Ratio,Combined Score,Genes
0,MSigDB_Hallmark_2020,UV Response Up,0.033584,0.877524,0,0,3.539931,12.013506,PTPRD;CA2;CEBPG;ENO2
1,MSigDB_Hallmark_2020,IL-2/STAT5 Signaling,0.104338,0.877524,0,0,2.346065,5.302379,CA2;SPRY4;PHLDA1;HK2
2,MSigDB_Hallmark_2020,Myogenesis,0.108116,0.877524,0,0,2.076367,4.618978,ACHE;NCAM1;TPD52L1;CRYAB;PVALB
3,MSigDB_Hallmark_2020,Glycolysis,0.113682,0.877524,0,0,2.684141,5.836261,G6PD;ENO2;HK2
4,MSigDB_Hallmark_2020,Bile Acid Metabolism,0.132958,0.877524,0,0,3.347755,6.754835,DIO1;RBP1

Thyroid
For Thyroid top 150 correction type = FDR
Doing for top 150 gene

,gene_name,p_value,tissue,snp_id,beta,qv,maf,cluster_i,gene_chr,gene_start,gene_end
1,CENPJ,8.820354e-31,Thyroid,chr9_97772921_C_G_b38,0.693229,1.868592e-27,0.668831,2,chr13,24882284,24922889
4,TPTE2P1,1.870313e-27,Thyroid,chr9_97772921_C_G_b38,0.654771,1.584903e-24,0.668831,2,chr13,24924677,24968487
6,CPAMD8,1.325091e-19,Thyroid,chr9_97772921_C_G_b38,0.511589,8.020586e-17,0.668831,2,chr19,16892947,17026815
7,DTX4,3.129176e-19,Thyroid,chr9_97772921_C_G_b38,0.543535,1.657290e-16,0.668831,2,chr11,59171430,59208509
10,RP11-756A22.7,5.134648e-18,Thyroid,chr9_97772921_C_G_b38,0.533252,1.977773e-15,0.668831,2,chr13,24933006,24936796

,Gene_set,Term,P-value,Adjusted P-value,Old P-value,Old adjusted P-value,Odds Ratio,Combined Score,Genes
0,MSigDB_Hallmark_2020,Estrogen Response Early,0.003970,0.134987,0,0,3.476490,19.221292,SULT2B1;MUC1;MLPH;TMPRSS3;RHOBTB3;TFF3;INHBB;C...
1,MSigDB_Hallmark_2020,Pancreas Beta Cells,0.014570,0.239199,0,0,6.911565,29.227543,PCSK2;NKX6-1;FOXA2
2,MSigDB_Hallmark_2020,Estrogen Response Late,0.021106,0.239199,0,0,2.722222,10.502902,SULT2B1;ISG20;MDK;TNNC1;DLG5;TMPRSS3;TFF3
3,MSigDB_Hallmark_2020,Hedgehog Signaling,0.065426,0.468150,0,0,5.494595,14.982864,CELSR1;NKX6-1
4,MSigDB_Hallmark_2020,Bile Acid Metabolism,0.068846,0.468150,0,0,3.445578,9.219983,SULT2B1;DHCR24;HSD17B6

Doing for top 150 gene

,gene_name,p_value,tissue,snp_id,beta,qv,maf,cluster_i,gene_chr,gene_start,gene_end
0,FAM163A,4.537380e-31,Thyroid,chr9_97772921_C_G_b38,-0.694002,1.868592e-27,0.668831,2,chr1,179743163,179816183
2,IGHE,1.957715e-30,Thyroid,chr9_97772921_C_G_b38,-0.650482,2.764947e-27,0.668831,2,chr14,105599941,105601728
3,FAM189A1,6.623082e-28,Thyroid,chr9_97772921_C_G_b38,-0.665878,7.015500e-25,0.668831,2,chr15,29120254,29570723
5,PLA2G4F,4.443909e-21,Thyroid,chr9_97772921_C_G_b38,-0.577363,3.138141e-18,0.668831,2,chr15,42139034,42156636
8,HK2,8.583262e-19,Thyroid,chr9_97772921_C_G_b38,-0.541636,4.040809e-16,0.668831,2,chr2,74833988,74893359

,Gene_set,Term,P-value,Adjusted P-value,Old P-value,Old adjusted P-value,Odds Ratio,Combined Score,Genes
0,MSigDB_Hallmark_2020,Glycolysis,0.030922,0.461528,0,0,3.088889,10.737912,G6PD;GCLC;CHST1;ENO2;HK2
1,MSigDB_Hallmark_2020,KRAS Signaling Dn,0.034529,0.461528,0,0,2.654101,8.933558,EPHA5;ATP4A;CD80;IGFBP2;YBX2;SLC6A3
2,MSigDB_Hallmark_2020,UV Response Up,0.035864,0.461528,0,0,2.955979,9.837568,PTPRD;CA2;CEBPG;IGFBP2;ENO2
3,MSigDB_Hallmark_2020,Spermatogenesis,0.046153,0.461528,0,0,4.138776,12.730039,CCNB2;YBX2;ACRBP
4,MSigDB_Hallmark_2020,Hedgehog Signaling,0.065426,0.523407,0,0,5.494595,14.982864,ACHE;NRCAM

Thyroid
For Thyroid top 200 correction type = FDR
Doing for top 200 gene

,gene_name,p_value,tissue,snp_id,beta,qv,maf,cluster_i,gene_chr,gene_start,gene_end
1,CENPJ,8.820354e-31,Thyroid,chr9_97772921_C_G_b38,0.693229,1.868592e-27,0.668831,2,chr13,24882284,24922889
4,TPTE2P1,1.870313e-27,Thyroid,chr9_97772921_C_G_b38,0.654771,1.584903e-24,0.668831,2,chr13,24924677,24968487
6,CPAMD8,1.325091e-19,Thyroid,chr9_97772921_C_G_b38,0.511589,8.020586e-17,0.668831,2,chr19,16892947,17026815
7,DTX4,3.129176e-19,Thyroid,chr9_97772921_C_G_b38,0.543535,1.657290e-16,0.668831,2,chr11,59171430,59208509
10,RP11-756A22.7,5.134648e-18,Thyroid,chr9_97772921_C_G_b38,0.533252,1.977773e-15,0.668831,2,chr13,24933006,24936796

,Gene_set,Term,P-value,Adjusted P-value,Old P-value,Old adjusted P-value,Odds Ratio,Combined Score,Genes
0,MSigDB_Hallmark_2020,Estrogen Response Early,0.006940,0.249857,0,0,2.917048,14.498856,SULT2B1;MUC1;MLPH;ELF3;TMPRSS3;TFF3;RHOBTB3;IN...
1,MSigDB_Hallmark_2020,Glycolysis,0.029174,0.261765,0,0,2.798969,9.892876,ISG20;ELF3;CITED2;TFF3;SOX9;CACNA1H
2,MSigDB_Hallmark_2020,Pancreas Beta Cells,0.031179,0.261765,0,0,5.093909,17.665698,PCSK2;NKX6-1;FOXA2
3,MSigDB_Hallmark_2020,Estrogen Response Late,0.031931,0.261765,0,0,2.321009,7.993989,SULT2B1;ISG20;ST6GALNAC2;MDK;TNNC1;TMPRSS3;DLG...
4,MSigDB_Hallmark_2020,Bile Acid Metabolism,0.036356,0.261765,0,0,3.551908,11.772409,SULT2B1;BBOX1;DHCR24;HSD17B6

Doing for top 200 gene

,gene_name,p_value,tissue,snp_id,beta,qv,maf,cluster_i,gene_chr,gene_start,gene_end
0,FAM163A,4.537380e-31,Thyroid,chr9_97772921_C_G_b38,-0.694002,1.868592e-27,0.668831,2,chr1,179743163,179816183
2,IGHE,1.957715e-30,Thyroid,chr9_97772921_C_G_b38,-0.650482,2.764947e-27,0.668831,2,chr14,105599941,105601728
3,FAM189A1,6.623082e-28,Thyroid,chr9_97772921_C_G_b38,-0.665878,7.015500e-25,0.668831,2,chr15,29120254,29570723
5,PLA2G4F,4.443909e-21,Thyroid,chr9_97772921_C_G_b38,-0.577363,3.138141e-18,0.668831,2,chr15,42139034,42156636
8,HK2,8.583262e-19,Thyroid,chr9_97772921_C_G_b38,-0.541636,4.040809e-16,0.668831,2,chr2,74833988,74893359

,Gene_set,Term,P-value,Adjusted P-value,Old P-value,Old adjusted P-value,Odds Ratio,Combined Score,Genes
0,MSigDB_Hallmark_2020,Spermatogenesis,0.003779,0.158717,0,0,5.709402,31.848755,CCNB2;GSTM3;HSPA4L;YBX2;ACRBP
1,MSigDB_Hallmark_2020,KRAS Signaling Dn,0.043096,0.565488,0,0,2.318904,7.291388,EPHA5;ATP4A;TGFB2;CD80;IGFBP2;YBX2;SLC6A3
2,MSigDB_Hallmark_2020,Estrogen Response Early,0.055655,0.565488,0,0,2.176166,6.286051,CYP26B1;DEPTOR;ZNF185;PODXL;MYOF;ABAT;TPD52L1
3,MSigDB_Hallmark_2020,DNA Repair,0.078085,0.565488,0,0,5.073232,12.936547,CETN2;CCNO
4,MSigDB_Hallmark_2020,Xenobiotic Metabolism,0.080373,0.565488,0,0,2.115891,5.334330,TGFB2;GCLC;ARG1;CA2;RAP1GAP;CYP17A1

Esophagus_Mucosa
For Esophagus_Mucosa top 50 correction type = FDR
Doing for top 50 gene

,gene_name,p_value,tissue,snp_id,beta,qv,maf,cluster_i,gene_chr,gene_start,gene_end
1,LAPTM4B,8.528937e-07,Esophagus_Mucosa,chr1_78663229_G_A_b38,0.314870,0.000697,0.547222,7,chr8,97775057,97853013
3,RANBP1,1.015402e-06,Esophagus_Mucosa,chr1_78663229_G_A_b38,0.314146,0.000697,0.547222,7,chr22,20115938,20127357
4,SAA1,1.125504e-06,Esophagus_Mucosa,chr1_78663229_G_A_b38,0.310825,0.000697,0.547222,7,chr11,18266174,18269977
9,IFI16,1.938679e-06,Esophagus_Mucosa,chr1_78663229_G_A_b38,0.307319,0.000759,0.547222,7,chr1,158999968,159055155
11,SLC43A3,2.615278e-06,Esophagus_Mucosa,chr1_78663229_G_A_b38,0.299144,0.000831,0.547222,7,chr11,57406954,57427580

,Gene_set,Term,P-value,Adjusted P-value,Old P-value,Old adjusted P-value,Odds Ratio,Combined Score,Genes
0,MSigDB_Hallmark_2020,E2F Targets,9.718127e-16,2.623894e-14,0,0,37.168056,1284.801875,RANBP1;DNMT1;SPAG5;BUB1B;PAICS;LMNB1;MELK;KIF1...
1,MSigDB_Hallmark_2020,Myc Targets V1,2.043786e-07,2.759112e-06,0,0,32.786932,505.026667,RANBP1;RFC4;MCM6;KPNA2;RRP9;HSPD1
2,MSigDB_Hallmark_2020,G2-M Checkpoint,4.590948e-06,4.131853e-05,0,0,12.938469,159.032210,UBE2C;TROAP;MCM3;TACC3;MCM6;KPNA2;LMNB1
3,MSigDB_Hallmark_2020,DNA Repair,3.014818e-04,2.035002e-03,0,0,30.757979,249.348815,RFC4;ADA;ZWINT
4,MSigDB_Hallmark_2020,Myc Targets V2,9.733132e-03,5.255892e-02,0,0,16.054167,74.366424,RRP9;HSPD1

Doing for top 50 gene

,gene_name,p_value,tissue,snp_id,beta,qv,maf,cluster_i,gene_chr,gene_start,gene_end
0,SLC24A3,4.151806e-07,Esophagus_Mucosa,chr1_78663229_G_A_b38,-0.323393,0.000697,0.547222,7,chr20,19212646,19722937
2,CRISP3,9.577293e-07,Esophagus_Mucosa,chr1_78663229_G_A_b38,-0.314357,0.000697,0.547222,7,chr6,49727384,49744437
5,UPK3B,1.128828e-06,Esophagus_Mucosa,chr1_78663229_G_A_b38,-0.312264,0.000697,0.547222,7,chr7,76510428,76516521
6,CAMK2N1,1.279904e-06,Esophagus_Mucosa,chr1_78663229_G_A_b38,-0.311924,0.000697,0.547222,7,chr1,20482391,20486220
7,CALB2,1.424056e-06,Esophagus_Mucosa,chr1_78663229_G_A_b38,-0.309081,0.000697,0.547222,7,chr16,71358713,71390438

,Gene_set,Term,P-value,Adjusted P-value,Old P-value,Old adjusted P-value,Odds Ratio,Combined Score,Genes
0,MSigDB_Hallmark_2020,IL-2/STAT5 Signaling,0.019076,0.400590,0,0,4.275551,16.928355,MAFF;ST3GAL4;SH3BGRL2;MXD1
1,MSigDB_Hallmark_2020,p53 Pathway,0.065446,0.422826,0,0,3.458663,9.430137,PMM1;MXD1;ZNF365
2,MSigDB_Hallmark_2020,Fatty Acid Metabolism,0.084086,0.422826,0,0,4.429398,10.966827,HPGD;MGLL
3,MSigDB_Hallmark_2020,Notch Signaling,0.109401,0.422826,0,0,9.834184,21.760428,DTX2
4,MSigDB_Hallmark_2020,Adipogenesis,0.116190,0.422826,0,0,3.616477,7.784564,CCNG2;MGLL

Esophagus_Mucosa
For Esophagus_Mucosa top 100 correction type = FDR
Doing for top 100 gene

,gene_name,p_value,tissue,snp_id,beta,qv,maf,cluster_i,gene_chr,gene_start,gene_end
1,LAPTM4B,8.528937e-07,Esophagus_Mucosa,chr1_78663229_G_A_b38,0.314870,0.000697,0.547222,7,chr8,97775057,97853013
3,RANBP1,1.015402e-06,Esophagus_Mucosa,chr1_78663229_G_A_b38,0.314146,0.000697,0.547222,7,chr22,20115938,20127357
4,SAA1,1.125504e-06,Esophagus_Mucosa,chr1_78663229_G_A_b38,0.310825,0.000697,0.547222,7,chr11,18266174,18269977
9,IFI16,1.938679e-06,Esophagus_Mucosa,chr1_78663229_G_A_b38,0.307319,0.000759,0.547222,7,chr1,158999968,159055155
11,SLC43A3,2.615278e-06,Esophagus_Mucosa,chr1_78663229_G_A_b38,0.299144,0.000831,0.547222,7,chr11,57406954,57427580

,Gene_set,Term,P-value,Adjusted P-value,Old P-value,Old adjusted P-value,Odds Ratio,Combined Score,Genes
0,MSigDB_Hallmark_2020,E2F Targets,5.044279e-32,1.765497e-30,0,0,56.643162,4081.959383,DNMT1;RNASEH2A;TFRC;HMGB2;BUB1B;AURKB;LMNB1;PT...
1,MSigDB_Hallmark_2020,G2-M Checkpoint,6.511218e-15,1.139463e-13,0,0,20.347178,664.645661,UBE2C;TROAP;PLK1;CDC6;AURKB;LMNB1;CCNA2;CDC45;...
2,MSigDB_Hallmark_2020,Myc Targets V1,9.730203e-13,1.135190e-11,0,0,42.719101,1181.540767,CCNA2;RANBP1;CCT2;RFC4;CDC45;MCM6;DEK;KPNA2;RR...
3,MSigDB_Hallmark_2020,Myc Targets V2,1.956984e-07,1.712361e-06,0,0,40.500000,625.590987,PLK1;TMEM97;IPO4;RRP9;SRM;HSPD1
4,MSigDB_Hallmark_2020,DNA Repair,1.154911e-04,8.084379e-04,0,0,22.654762,205.395249,FEN1;RFC4;ADA;ZWINT

Doing for top 100 gene

,gene_name,p_value,tissue,snp_id,beta,qv,maf,cluster_i,gene_chr,gene_start,gene_end
0,SLC24A3,4.151806e-07,Esophagus_Mucosa,chr1_78663229_G_A_b38,-0.323393,0.000697,0.547222,7,chr20,19212646,19722937
2,CRISP3,9.577293e-07,Esophagus_Mucosa,chr1_78663229_G_A_b38,-0.314357,0.000697,0.547222,7,chr6,49727384,49744437
5,UPK3B,1.128828e-06,Esophagus_Mucosa,chr1_78663229_G_A_b38,-0.312264,0.000697,0.547222,7,chr7,76510428,76516521
6,CAMK2N1,1.279904e-06,Esophagus_Mucosa,chr1_78663229_G_A_b38,-0.311924,0.000697,0.547222,7,chr1,20482391,20486220
7,CALB2,1.424056e-06,Esophagus_Mucosa,chr1_78663229_G_A_b38,-0.309081,0.000697,0.547222,7,chr16,71358713,71390438

,Gene_set,Term,P-value,Adjusted P-value,Old P-value,Old adjusted P-value,Odds Ratio,Combined Score,Genes
0,MSigDB_Hallmark_2020,Fatty Acid Metabolism,0.015229,0.223873,0,0,4.631127,19.379105,HPGD;TP53INP2;CIDEA;MGLL
1,MSigDB_Hallmark_2020,IL-2/STAT5 Signaling,0.016583,0.223873,0,0,3.181277,13.041218,MAFF;ST3GAL4;SH3BGRL2;EMP1;SNX9;MXD1
2,MSigDB_Hallmark_2020,Adipogenesis,0.111879,0.880653,0,0,2.711580,5.939280,CCNG2;CIDEA;MGLL
3,MSigDB_Hallmark_2020,Glycolysis,0.197028,0.880653,0,0,2.037982,3.310520,GYS2;B3GNT3;QSOX1
4,MSigDB_Hallmark_2020,Notch Signaling,0.208032,0.880653,0,0,4.804293,7.543056,DTX2

Esophagus_Mucosa
For Esophagus_Mucosa top 150 correction type = FDR
Doing for top 150 gene

,gene_name,p_value,tissue,snp_id,beta,qv,maf,cluster_i,gene_chr,gene_start,gene_end
1,LAPTM4B,8.528937e-07,Esophagus_Mucosa,chr1_78663229_G_A_b38,0.314870,0.000697,0.547222,7,chr8,97775057,97853013
3,RANBP1,1.015402e-06,Esophagus_Mucosa,chr1_78663229_G_A_b38,0.314146,0.000697,0.547222,7,chr22,20115938,20127357
4,SAA1,1.125504e-06,Esophagus_Mucosa,chr1_78663229_G_A_b38,0.310825,0.000697,0.547222,7,chr11,18266174,18269977
9,IFI16,1.938679e-06,Esophagus_Mucosa,chr1_78663229_G_A_b38,0.307319,0.000759,0.547222,7,chr1,158999968,159055155
11,SLC43A3,2.615278e-06,Esophagus_Mucosa,chr1_78663229_G_A_b38,0.299144,0.000831,0.547222,7,chr11,57406954,57427580

,Gene_set,Term,P-value,Adjusted P-value,Old P-value,Old adjusted P-value,Odds Ratio,Combined Score,Genes
0,MSigDB_Hallmark_2020,E2F Targets,4.488263e-42,1.750423e-40,0,0,74.178075,7062.279989,DNMT1;RNASEH2A;TFRC;HMGB2;BUB1B;MKI67;AURKB;LM...
1,MSigDB_Hallmark_2020,G2-M Checkpoint,4.388005e-28,8.556610e-27,0,0,35.352021,2226.947805,TROAP;MKI67;AURKB;LMNB1;CCNB2;CDC45;PTTG1;NUSA...
2,MSigDB_Hallmark_2020,Myc Targets V1,1.486220e-15,1.932085e-14,0,0,49.447368,1688.258787,RANBP1;CCT2;RFC4;DDX21;DEK;RRP9;HSPD1;SRM;CCNA...
3,MSigDB_Hallmark_2020,Myc Targets V2,6.201874e-08,6.046827e-07,0,0,37.610000,624.169136,PLK1;MCM5;TMEM97;IPO4;RRP9;SRM;HSPD1
4,MSigDB_Hallmark_2020,Mitotic Spindle,1.310578e-07,1.022251e-06,0,0,10.422667,165.174551,CCNB2;CENPF;PRC1;PLK1;CDK1;NUSAP1;BIRC5;KIF2C;...

Doing for top 150 gene

,gene_name,p_value,tissue,snp_id,beta,qv,maf,cluster_i,gene_chr,gene_start,gene_end
0,SLC24A3,4.151806e-07,Esophagus_Mucosa,chr1_78663229_G_A_b38,-0.323393,0.000697,0.547222,7,chr20,19212646,19722937
2,CRISP3,9.577293e-07,Esophagus_Mucosa,chr1_78663229_G_A_b38,-0.314357,0.000697,0.547222,7,chr6,49727384,49744437
5,UPK3B,1.128828e-06,Esophagus_Mucosa,chr1_78663229_G_A_b38,-0.312264,0.000697,0.547222,7,chr7,76510428,76516521
6,CAMK2N1,1.279904e-06,Esophagus_Mucosa,chr1_78663229_G_A_b38,-0.311924,0.000697,0.547222,7,chr1,20482391,20486220
7,CALB2,1.424056e-06,Esophagus_Mucosa,chr1_78663229_G_A_b38,-0.309081,0.000697,0.547222,7,chr16,71358713,71390438

,Gene_set,Term,P-value,Adjusted P-value,Old P-value,Old adjusted P-value,Odds Ratio,Combined Score,Genes
0,MSigDB_Hallmark_2020,Adipogenesis,0.007566,0.185768,0,0,3.878125,18.941048,RIOK3;CCNG2;CIDEA;SNCG;TOB1;MGLL
1,MSigDB_Hallmark_2020,IL-2/STAT5 Signaling,0.011610,0.185768,0,0,2.847772,12.689236,ECM1;MAFF;ST3GAL4;SH3BGRL2;EMP1;SNX9;MXD1;HOPX
2,MSigDB_Hallmark_2020,Fatty Acid Metabolism,0.055788,0.595068,0,0,3.004835,8.672562,HPGD;TP53INP2;CIDEA;MGLL
3,MSigDB_Hallmark_2020,Estrogen Response Early,0.134714,0.793344,0,0,1.931557,3.872003,CALB2;SLC24A3;TIPARP;ALDH3B1;TOB1
4,MSigDB_Hallmark_2020,p53 Pathway,0.146534,0.793344,0,0,1.873732,3.598494,PLK3;PMM1;MXD1;TOB1;ZNF365

Esophagus_Mucosa
For Esophagus_Mucosa top 200 correction type = FDR
Doing for top 200 gene

,gene_name,p_value,tissue,snp_id,beta,qv,maf,cluster_i,gene_chr,gene_start,gene_end
1,LAPTM4B,8.528937e-07,Esophagus_Mucosa,chr1_78663229_G_A_b38,0.314870,0.000697,0.547222,7,chr8,97775057,97853013
3,RANBP1,1.015402e-06,Esophagus_Mucosa,chr1_78663229_G_A_b38,0.314146,0.000697,0.547222,7,chr22,20115938,20127357
4,SAA1,1.125504e-06,Esophagus_Mucosa,chr1_78663229_G_A_b38,0.310825,0.000697,0.547222,7,chr11,18266174,18269977
9,IFI16,1.938679e-06,Esophagus_Mucosa,chr1_78663229_G_A_b38,0.307319,0.000759,0.547222,7,chr1,158999968,159055155
11,SLC43A3,2.615278e-06,Esophagus_Mucosa,chr1_78663229_G_A_b38,0.299144,0.000831,0.547222,7,chr11,57406954,57427580

,Gene_set,Term,P-value,Adjusted P-value,Old P-value,Old adjusted P-value,Odds Ratio,Combined Score,Genes
0,MSigDB_Hallmark_2020,E2F Targets,5.509070e-44,2.258719e-42,0,0,74.863412,7456.945969,TOP2A;DNMT1;RNASEH2A;TFRC;HMGB2;BUB1B;MKI67;AU...
1,MSigDB_Hallmark_2020,G2-M Checkpoint,1.440947e-31,2.953941e-30,0,0,36.701724,2606.366940,TOP2A;TROAP;KIF11;MKI67;AURKB;LMNB1;CDC20;CCNB...
2,MSigDB_Hallmark_2020,Myc Targets V1,1.232839e-20,1.684880e-19,0,0,93.318436,4277.939378,CCT2;RANBP1;RFC4;DDX21;DEK;TYMS;RRP9;HSPD1;SRM...
3,MSigDB_Hallmark_2020,Mitotic Spindle,2.017198e-11,2.067628e-10,0,0,13.598527,334.887200,TOP2A;PLK1;KIF23;KIF11;NDC80;LMNB1;TPX2;CCNB2;...
4,MSigDB_Hallmark_2020,Myc Targets V2,1.494238e-08,1.225275e-07,0,0,39.280423,707.796487,PLK1;MCM4;MCM5;TMEM97;IPO4;RRP9;SRM;HSPD1

Doing for top 200 gene

,gene_name,p_value,tissue,snp_id,beta,qv,maf,cluster_i,gene_chr,gene_start,gene_end
0,SLC24A3,4.151806e-07,Esophagus_Mucosa,chr1_78663229_G_A_b38,-0.323393,0.000697,0.547222,7,chr20,19212646,19722937
2,CRISP3,9.577293e-07,Esophagus_Mucosa,chr1_78663229_G_A_b38,-0.314357,0.000697,0.547222,7,chr6,49727384,49744437
5,UPK3B,1.128828e-06,Esophagus_Mucosa,chr1_78663229_G_A_b38,-0.312264,0.000697,0.547222,7,chr7,76510428,76516521
6,CAMK2N1,1.279904e-06,Esophagus_Mucosa,chr1_78663229_G_A_b38,-0.311924,0.000697,0.547222,7,chr1,20482391,20486220
7,CALB2,1.424056e-06,Esophagus_Mucosa,chr1_78663229_G_A_b38,-0.309081,0.000697,0.547222,7,chr16,71358713,71390438

,Gene_set,Term,P-value,Adjusted P-value,Old P-value,Old adjusted P-value,Odds Ratio,Combined Score,Genes
0,MSigDB_Hallmark_2020,IL-2/STAT5 Signaling,0.007593,0.258158,0,0,2.699778,13.176380,ECM1;MAFF;ST3GAL4;PIM1;SH3BGRL2;EMP1;SNX9;MXD1...
1,MSigDB_Hallmark_2020,Adipogenesis,0.028074,0.477264,0,0,2.839948,10.146847,RIOK3;CCNG2;CIDEA;SNCG;TOB1;MGLL
2,MSigDB_Hallmark_2020,Wnt-beta Catenin Signaling,0.089269,0.991583,0,0,4.678030,11.302609,DKK4;DKK1
3,MSigDB_Hallmark_2020,Fatty Acid Metabolism,0.126703,0.991583,0,0,2.208283,4.562118,HPGD;TP53INP2;CIDEA;MGLL
4,MSigDB_Hallmark_2020,heme Metabolism,0.264516,0.991583,0,0,1.751745,2.329566,RIOK3;FBXO34;LPIN2

Skin_Sun_Exposed_Lower_leg
For Skin_Sun_Exposed_Lower_leg top 50 correction type = FDR
Doing for top 50 gene

,gene_name,p_value,tissue,snp_id,beta,qv,maf,cluster_i,gene_chr,gene_start,gene_end
0,RP11-326C3.7,0.000201,Skin_Sun_Exposed_Lower_leg,chr5_174255970_A_G_b38,0.300963,0.451498,0.837278,2,chr11,310139,311141
1,RP11-574K11.24,0.000278,Skin_Sun_Exposed_Lower_leg,chr5_174255970_A_G_b38,0.297194,0.451498,0.837278,2,chr10,73742995,73744230
2,USP53,0.000462,Skin_Sun_Exposed_Lower_leg,chr5_174255970_A_G_b38,0.279352,0.451498,0.837278,2,chr4,119212645,119295517
3,AC112715.2,0.000662,Skin_Sun_Exposed_Lower_leg,chr5_174255970_A_G_b38,0.271122,0.517650,0.837278,2,chr2,237257091,237257676
4,RP11-585P4.5,0.001364,Skin_Sun_Exposed_Lower_leg,chr5_174255970_A_G_b38,0.263722,0.810098,0.837278,2,chr12,75483454,75489820

,Gene_set,Term,P-value,Adjusted P-value,Old P-value,Old adjusted P-value,Odds Ratio,Combined Score,Genes
0,MSigDB_Hallmark_2020,Apoptosis,0.008565,0.205555,0,0,5.505797,26.208116,TGFBR3;BNIP3L;TXNIP;AVPR1A
1,MSigDB_Hallmark_2020,Hypoxia,0.032161,0.385929,0,0,3.600573,12.375201,ERO1A;BNIP3L;MIF;PDK1
2,MSigDB_Hallmark_2020,Protein Secretion,0.132197,0.671190,0,0,7.855102,15.894489,ABCA1
3,MSigDB_Hallmark_2020,PI3K/AKT/mTOR Signaling,0.143329,0.671190,0,0,7.139147,13.868618,PDK1
4,MSigDB_Hallmark_2020,Glycolysis,0.164607,0.671190,0,0,2.881818,5.199354,ERO1A;MIF

Doing for top 50 gene

,gene_name,p_value,tissue,snp_id,beta,qv,maf,cluster_i,gene_chr,gene_start,gene_end
15,HIST1H1D,0.004015,Skin_Sun_Exposed_Lower_leg,chr5_174255970_A_G_b38,-0.230477,0.810098,0.837278,2,chr6,26234268,26234933
31,MMP28,0.007030,Skin_Sun_Exposed_Lower_leg,chr5_174255970_A_G_b38,-0.213391,0.810098,0.837278,2,chr17,35756249,35795707
34,CFAP157,0.008356,Skin_Sun_Exposed_Lower_leg,chr5_174255970_A_G_b38,-0.216319,0.822372,0.837278,2,chr9,127706992,127715337
35,HIST1H1E,0.008559,Skin_Sun_Exposed_Lower_leg,chr5_174255970_A_G_b38,-0.214718,0.822372,0.837278,2,chr6,26156354,26157107
38,C14orf80,0.009800,Skin_Sun_Exposed_Lower_leg,chr5_174255970_A_G_b38,-0.210532,0.822372,0.837278,2,chr14,105489855,105499575

,Gene_set,Term,P-value,Adjusted P-value,Old P-value,Old adjusted P-value,Odds Ratio,Combined Score,Genes
0,MSigDB_Hallmark_2020,Myogenesis,0.435758,0.710043,0,0,1.381268,1.147377,PKIA;MYOM2
1,MSigDB_Hallmark_2020,Interferon Alpha Response,0.448789,0.710043,0,0,1.729705,1.385844,IFI35
2,MSigDB_Hallmark_2020,UV Response Up,0.476788,0.710043,0,0,1.586839,1.175344,STIP1
3,MSigDB_Hallmark_2020,Glycolysis,0.522471,0.710043,0,0,1.385933,0.899728,TSTA3
4,MSigDB_Hallmark_2020,Epithelial Mesenchymal Transition,0.570794,0.710043,0,0,1.059646,0.594173,COL5A3;APLP1

Skin_Sun_Exposed_Lower_leg
For Skin_Sun_Exposed_Lower_leg top 100 correction type = FDR
Doing for top 100 gene

,gene_name,p_value,tissue,snp_id,beta,qv,maf,cluster_i,gene_chr,gene_start,gene_end
0,RP11-326C3.7,0.000201,Skin_Sun_Exposed_Lower_leg,chr5_174255970_A_G_b38,0.300963,0.451498,0.837278,2,chr11,310139,311141
1,RP11-574K11.24,0.000278,Skin_Sun_Exposed_Lower_leg,chr5_174255970_A_G_b38,0.297194,0.451498,0.837278,2,chr10,73742995,73744230
2,USP53,0.000462,Skin_Sun_Exposed_Lower_leg,chr5_174255970_A_G_b38,0.279352,0.451498,0.837278,2,chr4,119212645,119295517
3,AC112715.2,0.000662,Skin_Sun_Exposed_Lower_leg,chr5_174255970_A_G_b38,0.271122,0.517650,0.837278,2,chr2,237257091,237257676
4,RP11-585P4.5,0.001364,Skin_Sun_Exposed_Lower_leg,chr5_174255970_A_G_b38,0.263722,0.810098,0.837278,2,chr12,75483454,75489820

,Gene_set,Term,P-value,Adjusted P-value,Old P-value,Old adjusted P-value,Odds Ratio,Combined Score,Genes
0,MSigDB_Hallmark_2020,Hypoxia,0.032164,0.842115,0,0,2.697354,9.270577,ERO1A;BNIP3L;MIF;PPFIA4;PFKP;PDK1
1,MSigDB_Hallmark_2020,Glycolysis,0.055047,0.842115,0,0,2.984707,8.654373,ERO1A;MIF;PPFIA4;PFKP
2,MSigDB_Hallmark_2020,Apoptosis,0.077608,0.842115,0,0,2.631579,6.726533,TGFBR3;BNIP3L;TXNIP;AVPR1A
3,MSigDB_Hallmark_2020,Inflammatory Response,0.219281,0.842115,0,0,1.720763,2.611089,ABCA1;OSMR;SLC7A2;TLR2
4,MSigDB_Hallmark_2020,Wnt-beta Catenin Signaling,0.246135,0.842115,0,0,3.877551,5.435842,DKK1

Doing for top 100 gene

,gene_name,p_value,tissue,snp_id,beta,qv,maf,cluster_i,gene_chr,gene_start,gene_end
15,HIST1H1D,0.004015,Skin_Sun_Exposed_Lower_leg,chr5_174255970_A_G_b38,-0.230477,0.810098,0.837278,2,chr6,26234268,26234933
31,MMP28,0.007030,Skin_Sun_Exposed_Lower_leg,chr5_174255970_A_G_b38,-0.213391,0.810098,0.837278,2,chr17,35756249,35795707
34,CFAP157,0.008356,Skin_Sun_Exposed_Lower_leg,chr5_174255970_A_G_b38,-0.216319,0.822372,0.837278,2,chr9,127706992,127715337
35,HIST1H1E,0.008559,Skin_Sun_Exposed_Lower_leg,chr5_174255970_A_G_b38,-0.214718,0.822372,0.837278,2,chr6,26156354,26157107
38,C14orf80,0.009800,Skin_Sun_Exposed_Lower_leg,chr5_174255970_A_G_b38,-0.210532,0.822372,0.837278,2,chr14,105489855,105499575

,Gene_set,Term,P-value,Adjusted P-value,Old P-value,Old adjusted P-value,Odds Ratio,Combined Score,Genes
0,MSigDB_Hallmark_2020,E2F Targets,0.002456,0.066320,0,0,8.311404,49.944039,CDC20;BIRC5;TK1;ASF1B
1,MSigDB_Hallmark_2020,KRAS Signaling Dn,0.006820,0.092066,0,0,3.921870,19.562046,GAMT;LFNG;RYR1;AKR1B10;CLPS;WNT16
2,MSigDB_Hallmark_2020,UV Response Up,0.037821,0.225416,0,0,3.408514,11.162471,DNAJA1;STIP1;FMO1;FKBP4
3,MSigDB_Hallmark_2020,G2-M Checkpoint,0.040021,0.225416,0,0,4.332188,13.942461,CDC20;TROAP;BIRC5
4,MSigDB_Hallmark_2020,Xenobiotic Metabolism,0.041744,0.225416,0,0,2.811278,8.929200,CYP2J2;CBR1;REG1A;FMO1;APOE

Skin_Sun_Exposed_Lower_leg
For Skin_Sun_Exposed_Lower_leg top 150 correction type = FDR
Doing for top 150 gene

,gene_name,p_value,tissue,snp_id,beta,qv,maf,cluster_i,gene_chr,gene_start,gene_end
0,RP11-326C3.7,0.000201,Skin_Sun_Exposed_Lower_leg,chr5_174255970_A_G_b38,0.300963,0.451498,0.837278,2,chr11,310139,311141
1,RP11-574K11.24,0.000278,Skin_Sun_Exposed_Lower_leg,chr5_174255970_A_G_b38,0.297194,0.451498,0.837278,2,chr10,73742995,73744230
2,USP53,0.000462,Skin_Sun_Exposed_Lower_leg,chr5_174255970_A_G_b38,0.279352,0.451498,0.837278,2,chr4,119212645,119295517
3,AC112715.2,0.000662,Skin_Sun_Exposed_Lower_leg,chr5_174255970_A_G_b38,0.271122,0.517650,0.837278,2,chr2,237257091,237257676
4,RP11-585P4.5,0.001364,Skin_Sun_Exposed_Lower_leg,chr5_174255970_A_G_b38,0.263722,0.810098,0.837278,2,chr12,75483454,75489820

,Gene_set,Term,P-value,Adjusted P-value,Old P-value,Old adjusted P-value,Odds Ratio,Combined Score,Genes
0,MSigDB_Hallmark_2020,Glycolysis,0.020267,0.516795,0,0,3.051419,11.896821,ERO1A;STC1;MIF;MERTK;PPFIA4;PFKP
1,MSigDB_Hallmark_2020,Hypoxia,0.027200,0.516795,0,0,2.395370,8.634224,ERO1A;BNIP3L;GBE1;STC1;MIF;PPFIA4;PFKP;PDK1
2,MSigDB_Hallmark_2020,UV Response Dn,0.148825,0.960079,0,0,2.046897,3.899309,TGFBR3;CELF2;LPAR1;FBLN5
3,MSigDB_Hallmark_2020,Inflammatory Response,0.152598,0.960079,0,0,1.730651,3.253539,ABCA1;GPR183;LPAR1;OSMR;SLC7A2;TLR2
4,MSigDB_Hallmark_2020,Apoptosis,0.226155,0.960079,0,0,1.701149,2.528819,TGFBR3;BNIP3L;TXNIP;AVPR1A

Doing for top 150 gene

,gene_name,p_value,tissue,snp_id,beta,qv,maf,cluster_i,gene_chr,gene_start,gene_end
15,HIST1H1D,0.004015,Skin_Sun_Exposed_Lower_leg,chr5_174255970_A_G_b38,-0.230477,0.810098,0.837278,2,chr6,26234268,26234933
31,MMP28,0.007030,Skin_Sun_Exposed_Lower_leg,chr5_174255970_A_G_b38,-0.213391,0.810098,0.837278,2,chr17,35756249,35795707
34,CFAP157,0.008356,Skin_Sun_Exposed_Lower_leg,chr5_174255970_A_G_b38,-0.216319,0.822372,0.837278,2,chr9,127706992,127715337
35,HIST1H1E,0.008559,Skin_Sun_Exposed_Lower_leg,chr5_174255970_A_G_b38,-0.214718,0.822372,0.837278,2,chr6,26156354,26157107
38,C14orf80,0.009800,Skin_Sun_Exposed_Lower_leg,chr5_174255970_A_G_b38,-0.210532,0.822372,0.837278,2,chr14,105489855,105499575

,Gene_set,Term,P-value,Adjusted P-value,Old P-value,Old adjusted P-value,Odds Ratio,Combined Score,Genes
0,MSigDB_Hallmark_2020,KRAS Signaling Dn,0.000194,0.006775,0,0,4.639098,39.663518,GAMT;LFNG;RYR1;AKR1B10;CLPS;CPB1;KRT1;GP2;WNT1...
1,MSigDB_Hallmark_2020,E2F Targets,0.001495,0.026168,0,0,7.166667,46.622237,CDC20;RRM2;BIRC5;TK1;ASF1B
2,MSigDB_Hallmark_2020,Xenobiotic Metabolism,0.023805,0.229730,0,0,2.657034,9.931626,CYP2J2;CBR1;NQO1;REG1A;FMO1;APOE;PSMB10
3,MSigDB_Hallmark_2020,G2-M Checkpoint,0.026255,0.229730,0,0,3.933614,14.317971,CDC20;UBE2C;TROAP;BIRC5
4,MSigDB_Hallmark_2020,UV Response Up,0.123546,0.864824,0,0,2.211435,4.624420,DNAJA1;STIP1;FMO1;FKBP4

Skin_Sun_Exposed_Lower_leg
For Skin_Sun_Exposed_Lower_leg top 200 correction type = FDR
Doing for top 200 gene

,gene_name,p_value,tissue,snp_id,beta,qv,maf,cluster_i,gene_chr,gene_start,gene_end
0,RP11-326C3.7,0.000201,Skin_Sun_Exposed_Lower_leg,chr5_174255970_A_G_b38,0.300963,0.451498,0.837278,2,chr11,310139,311141
1,RP11-574K11.24,0.000278,Skin_Sun_Exposed_Lower_leg,chr5_174255970_A_G_b38,0.297194,0.451498,0.837278,2,chr10,73742995,73744230
2,USP53,0.000462,Skin_Sun_Exposed_Lower_leg,chr5_174255970_A_G_b38,0.279352,0.451498,0.837278,2,chr4,119212645,119295517
3,AC112715.2,0.000662,Skin_Sun_Exposed_Lower_leg,chr5_174255970_A_G_b38,0.271122,0.517650,0.837278,2,chr2,237257091,237257676
4,RP11-585P4.5,0.001364,Skin_Sun_Exposed_Lower_leg,chr5_174255970_A_G_b38,0.263722,0.810098,0.837278,2,chr12,75483454,75489820

,Gene_set,Term,P-value,Adjusted P-value,Old P-value,Old adjusted P-value,Odds Ratio,Combined Score,Genes
0,MSigDB_Hallmark_2020,Glycolysis,0.067727,0.772403,0,0,2.230418,6.004903,ERO1A;STC1;MIF;MERTK;PPFIA4;PFKP
1,MSigDB_Hallmark_2020,Wnt-beta Catenin Signaling,0.104837,0.772403,0,0,4.174845,9.415744,DLL1;DKK1
2,MSigDB_Hallmark_2020,Protein Secretion,0.104837,0.772403,0,0,4.174845,9.415744,ABCA1;BNIP3
3,MSigDB_Hallmark_2020,Hypoxia,0.108658,0.772403,0,0,1.744238,3.871427,ERO1A;BNIP3L;GBE1;STC1;MIF;PPFIA4;PFKP;PDK1
4,MSigDB_Hallmark_2020,Inflammatory Response,0.108658,0.772403,0,0,1.744238,3.871427,ABCA1;MARCO;GPR183;NAMPT;LPAR1;OSMR;SLC7A2;TLR2

Doing for top 200 gene

,gene_name,p_value,tissue,snp_id,beta,qv,maf,cluster_i,gene_chr,gene_start,gene_end
15,HIST1H1D,0.004015,Skin_Sun_Exposed_Lower_leg,chr5_174255970_A_G_b38,-0.230477,0.810098,0.837278,2,chr6,26234268,26234933
31,MMP28,0.007030,Skin_Sun_Exposed_Lower_leg,chr5_174255970_A_G_b38,-0.213391,0.810098,0.837278,2,chr17,35756249,35795707
34,CFAP157,0.008356,Skin_Sun_Exposed_Lower_leg,chr5_174255970_A_G_b38,-0.216319,0.822372,0.837278,2,chr9,127706992,127715337
35,HIST1H1E,0.008559,Skin_Sun_Exposed_Lower_leg,chr5_174255970_A_G_b38,-0.214718,0.822372,0.837278,2,chr6,26156354,26157107
38,C14orf80,0.009800,Skin_Sun_Exposed_Lower_leg,chr5_174255970_A_G_b38,-0.210532,0.822372,0.837278,2,chr14,105489855,105499575

,Gene_set,Term,P-value,Adjusted P-value,Old P-value,Old adjusted P-value,Odds Ratio,Combined Score,Genes
0,MSigDB_Hallmark_2020,KRAS Signaling Dn,0.000490,0.018636,0,0,3.796580,28.930832,GAMT;RYR1;LFNG;CLPS;AKR1B10;SERPINB2;CPB1;KRT1...
1,MSigDB_Hallmark_2020,Xenobiotic Metabolism,0.001304,0.024781,0,0,3.314732,22.016896,CYP2J2;CBR1;NQO1;CA2;CYP2S1;ID2;REG1A;FMO1;GST...
2,MSigDB_Hallmark_2020,E2F Targets,0.005270,0.066753,0,0,5.257835,27.581183,CDC20;RRM2;BIRC5;TK1;ASF1B
3,MSigDB_Hallmark_2020,Estrogen Response Late,0.007646,0.072634,0,0,2.696812,13.143205,CDC20;SCUBE2;TSTA3;CLIC3;CISH;CA2;ID2;ANXA9;FK...
4,MSigDB_Hallmark_2020,G2-M Checkpoint,0.016696,0.126890,0,0,3.778462,15.463681,CDC20;CDC45;UBE2C;TROAP;BIRC5

Adipose_Subcutaneous
For Adipose_Subcutaneous top 50 correction type = FDR
Doing for top 50 gene

,gene_name,p_value,tissue,snp_id,beta,qv,maf,cluster_i,gene_chr,gene_start,gene_end
0,SPX,0.000090,Adipose_Subcutaneous,chr10_17384475_A_C_b38,0.283536,0.276953,0.769494,1,chr12,21526307,21537377
8,MYZAP,0.000984,Adipose_Subcutaneous,chr10_17384475_A_C_b38,0.231936,0.357333,0.769494,1,chr15,57591941,57685364
12,LINC01485,0.001189,Adipose_Subcutaneous,chr10_17384475_A_C_b38,0.230094,0.363130,0.769494,1,chr5,173786790,173809039
19,MUC7,0.002312,Adipose_Subcutaneous,chr10_17384475_A_C_b38,0.186557,0.448736,0.769494,1,chr4,70430492,70482997
25,HSPB7,0.003147,Adipose_Subcutaneous,chr10_17384475_A_C_b38,0.210125,0.480630,0.769494,1,chr1,16014028,16019594

,Gene_set,Term,P-value,Adjusted P-value,Old P-value,Old adjusted P-value,Odds Ratio,Combined Score,Genes
0,MSigDB_Hallmark_2020,Adipogenesis,0.000002,0.000042,0,0,12.034348,160.085520,SLC25A1;GPAM;RETSAT;FZD4;LEP;ME1;ELOVL6;DHCR7
1,MSigDB_Hallmark_2020,mTORC1 Signaling,0.000500,0.006249,0,0,6.888158,52.357418,ELOVL5;SCD;ME1;ELOVL6;VLDLR;DHCR7
2,MSigDB_Hallmark_2020,Fatty Acid Metabolism,0.003882,0.032349,0,0,7.005435,38.890188,RETSAT;ELOVL5;FASN;ME1
3,MSigDB_Hallmark_2020,Estrogen Response Early,0.005351,0.033445,0,0,4.947028,25.875040,CALB2;ELOVL5;KRT15;FASN;DHCR7
4,MSigDB_Hallmark_2020,Cholesterol Homeostasis,0.014369,0.059870,0,0,6.512318,27.629824,SCD;FASN;DHCR7

Doing for top 50 gene

,gene_name,p_value,tissue,snp_id,beta,qv,maf,cluster_i,gene_chr,gene_start,gene_end
1,C4B,0.000139,Adipose_Subcutaneous,chr10_17384475_A_C_b38,-0.270787,0.276953,0.769494,1,chr6,32014762,32035418
2,TPGS1,0.000430,Adipose_Subcutaneous,chr10_17384475_A_C_b38,-0.255081,0.332200,0.769494,1,chr19,507834,519654
3,HLX,0.000486,Adipose_Subcutaneous,chr10_17384475_A_C_b38,-0.250685,0.332200,0.769494,1,chr1,220879400,220885059
4,JUND,0.000568,Adipose_Subcutaneous,chr10_17384475_A_C_b38,-0.241491,0.332200,0.769494,1,chr19,18279760,18281622
5,JUN,0.000581,Adipose_Subcutaneous,chr10_17384475_A_C_b38,-0.234458,0.332200,0.769494,1,chr1,58780788,58784327

,Gene_set,Term,P-value,Adjusted P-value,Old P-value,Old adjusted P-value,Odds Ratio,Combined Score,Genes
0,MSigDB_Hallmark_2020,TNF-alpha Signaling via NF-kB,1.723534e-12,5.687661e-11,0,0,15.411765,417.452992,PPP1R15A;DUSP5;JUN;CEBPD;GADD45A;DUSP1;FOS;CXC...
1,MSigDB_Hallmark_2020,p53 Pathway,4.397842e-05,7.256439e-04,0,0,8.813626,88.416634,PPP1R15A;JUN;GADD45A;FOS;MXD1;ATF3;HBEGF
2,MSigDB_Hallmark_2020,Inflammatory Response,1.843711e-03,1.757424e-02,0,0,5.256198,33.092894,CCRL2;IRF7;MXD1;SELE;CX3CL1;HBEGF
3,MSigDB_Hallmark_2020,Hypoxia,2.130210e-03,1.757424e-02,0,0,5.097594,31.358023,PPP1R15A;JUN;ZFP36;DUSP1;FOS;ATF3
4,MSigDB_Hallmark_2020,TGF-beta Signaling,2.324497e-02,1.534168e-01,0,0,9.553922,35.938668,PPP1R15A;JUNB

Adipose_Subcutaneous
For Adipose_Subcutaneous top 100 correction type = FDR
Doing for top 100 gene

,gene_name,p_value,tissue,snp_id,beta,qv,maf,cluster_i,gene_chr,gene_start,gene_end
0,SPX,0.000090,Adipose_Subcutaneous,chr10_17384475_A_C_b38,0.283536,0.276953,0.769494,1,chr12,21526307,21537377
8,MYZAP,0.000984,Adipose_Subcutaneous,chr10_17384475_A_C_b38,0.231936,0.357333,0.769494,1,chr15,57591941,57685364
12,LINC01485,0.001189,Adipose_Subcutaneous,chr10_17384475_A_C_b38,0.230094,0.363130,0.769494,1,chr5,173786790,173809039
19,MUC7,0.002312,Adipose_Subcutaneous,chr10_17384475_A_C_b38,0.186557,0.448736,0.769494,1,chr4,70430492,70482997
25,HSPB7,0.003147,Adipose_Subcutaneous,chr10_17384475_A_C_b38,0.210125,0.480630,0.769494,1,chr1,16014028,16019594

,Gene_set,Term,P-value,Adjusted P-value,Old P-value,Old adjusted P-value,Odds Ratio,Combined Score,Genes
0,MSigDB_Hallmark_2020,Fatty Acid Metabolism,0.000037,0.001227,0,0,7.551383,77.022766,NSDHL;RETSAT;ELOVL5;ACSL1;FASN;GPD1;ME1;DHCR24
1,MSigDB_Hallmark_2020,Adipogenesis,0.000290,0.004785,0,0,5.422666,44.170932,SLC25A1;GPAM;RETSAT;FZD4;LEP;ME1;ELOVL6;DHCR7
2,MSigDB_Hallmark_2020,Cholesterol Homeostasis,0.000487,0.005355,0,0,6.984802,53.277026,NSDHL;ACSS2;SCD;FASN;ALDOC;DHCR7
3,MSigDB_Hallmark_2020,mTORC1 Signaling,0.000944,0.007785,0,0,4.454759,31.030842,ELOVL5;SCD;ME1;ELOVL6;DHCR24;VLDLR;DHCR7;ACACA
4,MSigDB_Hallmark_2020,Pperoxisome,0.006308,0.041631,0,0,6.152244,31.167206,RETSAT;ELOVL5;ACSL1;DHCR24

Doing for top 100 gene

,gene_name,p_value,tissue,snp_id,beta,qv,maf,cluster_i,gene_chr,gene_start,gene_end
1,C4B,0.000139,Adipose_Subcutaneous,chr10_17384475_A_C_b38,-0.270787,0.276953,0.769494,1,chr6,32014762,32035418
2,TPGS1,0.000430,Adipose_Subcutaneous,chr10_17384475_A_C_b38,-0.255081,0.332200,0.769494,1,chr19,507834,519654
3,HLX,0.000486,Adipose_Subcutaneous,chr10_17384475_A_C_b38,-0.250685,0.332200,0.769494,1,chr1,220879400,220885059
4,JUND,0.000568,Adipose_Subcutaneous,chr10_17384475_A_C_b38,-0.241491,0.332200,0.769494,1,chr19,18279760,18281622
5,JUN,0.000581,Adipose_Subcutaneous,chr10_17384475_A_C_b38,-0.234458,0.332200,0.769494,1,chr1,58780788,58784327

,Gene_set,Term,P-value,Adjusted P-value,Old P-value,Old adjusted P-value,Odds Ratio,Combined Score,Genes
0,MSigDB_Hallmark_2020,TNF-alpha Signaling via NF-kB,4.443797e-14,1.733081e-12,0,0,10.292863,316.450803,PPP1R15A;DUSP5;JUN;CEBPD;GADD45A;DUSP1;TNFAIP3...
1,MSigDB_Hallmark_2020,p53 Pathway,6.745234e-04,1.315321e-02,0,0,4.714286,34.421377,PPP1R15A;JUN;GADD45A;FOS;MXD1;ATF3;HBEGF;ZFP36L1
2,MSigDB_Hallmark_2020,Hypoxia,1.420051e-03,1.846067e-02,0,0,3.762238,24.669227,PPP1R15A;ERO1A;JUN;ZFP36;CDKN1B;DUSP1;TNFAIP3;...
3,MSigDB_Hallmark_2020,Inflammatory Response,4.583627e-03,3.670387e-02,0,0,3.377857,18.190657,CXCL8;CCRL2;IRF7;OLR1;MXD1;SELE;CX3CL1;HBEGF
4,MSigDB_Hallmark_2020,Apoptosis,4.705624e-03,3.670387e-02,0,0,4.264278,22.852251,JUN;WEE1;CDKN1B;GADD45A;MMP2;ATF3

Adipose_Subcutaneous
For Adipose_Subcutaneous top 150 correction type = FDR
Doing for top 150 gene

,gene_name,p_value,tissue,snp_id,beta,qv,maf,cluster_i,gene_chr,gene_start,gene_end
0,SPX,0.000090,Adipose_Subcutaneous,chr10_17384475_A_C_b38,0.283536,0.276953,0.769494,1,chr12,21526307,21537377
8,MYZAP,0.000984,Adipose_Subcutaneous,chr10_17384475_A_C_b38,0.231936,0.357333,0.769494,1,chr15,57591941,57685364
12,LINC01485,0.001189,Adipose_Subcutaneous,chr10_17384475_A_C_b38,0.230094,0.363130,0.769494,1,chr5,173786790,173809039
19,MUC7,0.002312,Adipose_Subcutaneous,chr10_17384475_A_C_b38,0.186557,0.448736,0.769494,1,chr4,70430492,70482997
25,HSPB7,0.003147,Adipose_Subcutaneous,chr10_17384475_A_C_b38,0.210125,0.480630,0.769494,1,chr1,16014028,16019594

,Gene_set,Term,P-value,Adjusted P-value,Old P-value,Old adjusted P-value,Odds Ratio,Combined Score,Genes
0,MSigDB_Hallmark_2020,Fatty Acid Metabolism,0.000018,0.000664,0,0,6.416667,70.126556,NSDHL;RETSAT;MDH1;ELOVL5;ACSL1;FASN;GPD1;ME1;D...
1,MSigDB_Hallmark_2020,Adipogenesis,0.000043,0.000800,0,0,5.126147,51.513118,SLC25A1;LIPE;GPAM;RETSAT;FZD4;LEP;GBE1;ME1;ELO...
2,MSigDB_Hallmark_2020,Pperoxisome,0.000742,0.008454,0,0,6.581597,47.432414,ABCD2;RETSAT;ACSL1;ELOVL5;ALB;DHCR24
3,MSigDB_Hallmark_2020,mTORC1 Signaling,0.000914,0.008454,0,0,3.713294,25.984612,ELOVL5;SCD;GBE1;ME1;ELOVL6;DHCR24;VLDLR;DHCR7;...
4,MSigDB_Hallmark_2020,Cholesterol Homeostasis,0.003985,0.029485,0,0,4.500000,24.864035,NSDHL;ACSS2;SCD;FASN;ALDOC;DHCR7

Doing for top 150 gene

,gene_name,p_value,tissue,snp_id,beta,qv,maf,cluster_i,gene_chr,gene_start,gene_end
1,C4B,0.000139,Adipose_Subcutaneous,chr10_17384475_A_C_b38,-0.270787,0.276953,0.769494,1,chr6,32014762,32035418
2,TPGS1,0.000430,Adipose_Subcutaneous,chr10_17384475_A_C_b38,-0.255081,0.332200,0.769494,1,chr19,507834,519654
3,HLX,0.000486,Adipose_Subcutaneous,chr10_17384475_A_C_b38,-0.250685,0.332200,0.769494,1,chr1,220879400,220885059
4,JUND,0.000568,Adipose_Subcutaneous,chr10_17384475_A_C_b38,-0.241491,0.332200,0.769494,1,chr19,18279760,18281622
5,JUN,0.000581,Adipose_Subcutaneous,chr10_17384475_A_C_b38,-0.234458,0.332200,0.769494,1,chr1,58780788,58784327

,Gene_set,Term,P-value,Adjusted P-value,Old P-value,Old adjusted P-value,Odds Ratio,Combined Score,Genes
0,MSigDB_Hallmark_2020,TNF-alpha Signaling via NF-kB,1.931866e-15,7.727464e-14,0,0,8.637407,292.637845,PPP1R15A;PTGER4;CEBPD;TNFAIP3;SLC2A3;CXCL3;ETS...
1,MSigDB_Hallmark_2020,Hypoxia,4.326648e-05,8.653295e-04,0,0,4.074937,40.945511,PPP1R15A;ERO1A;JUN;CDKN1B;TES;DUSP1;TNFAIP3;ST...
2,MSigDB_Hallmark_2020,p53 Pathway,2.440482e-03,3.253976e-02,0,0,3.465310,20.845778,PPP1R15A;JUN;GADD45A;FOS;MXD1;KLF4;ATF3;HBEGF;...
3,MSigDB_Hallmark_2020,Interferon Alpha Response,3.508818e-03,3.508818e-02,0,0,4.633578,26.191192,CD74;IFI27;CCRL2;MX1;IRF7;ISG15
4,MSigDB_Hallmark_2020,Inflammatory Response,5.853758e-03,4.683006e-02,0,0,2.796992,14.378419,PTGER4;CXCL8;RGS1;CCRL2;IRF7;OLR1;MXD1;SELE;CX...

Adipose_Subcutaneous
For Adipose_Subcutaneous top 200 correction type = FDR
Doing for top 200 gene

,gene_name,p_value,tissue,snp_id,beta,qv,maf,cluster_i,gene_chr,gene_start,gene_end
0,SPX,0.000090,Adipose_Subcutaneous,chr10_17384475_A_C_b38,0.283536,0.276953,0.769494,1,chr12,21526307,21537377
8,MYZAP,0.000984,Adipose_Subcutaneous,chr10_17384475_A_C_b38,0.231936,0.357333,0.769494,1,chr15,57591941,57685364
12,LINC01485,0.001189,Adipose_Subcutaneous,chr10_17384475_A_C_b38,0.230094,0.363130,0.769494,1,chr5,173786790,173809039
19,MUC7,0.002312,Adipose_Subcutaneous,chr10_17384475_A_C_b38,0.186557,0.448736,0.769494,1,chr4,70430492,70482997
25,HSPB7,0.003147,Adipose_Subcutaneous,chr10_17384475_A_C_b38,0.210125,0.480630,0.769494,1,chr1,16014028,16019594

,Gene_set,Term,P-value,Adjusted P-value,Old P-value,Old adjusted P-value,Odds Ratio,Combined Score,Genes
0,MSigDB_Hallmark_2020,Adipogenesis,0.000006,0.000220,0,0,5.077224,61.230637,SLC25A1;RETSAT;FZD4;GBE1;ADIPOQ;ELOVL6;FAH;ADI...
1,MSigDB_Hallmark_2020,Fatty Acid Metabolism,0.000210,0.003983,0,0,4.665414,39.517331,NSDHL;RETSAT;MDH1;ACSL1;ELOVL5;FASN;GPD1;ME1;D...
2,MSigDB_Hallmark_2020,Oxidative Phosphorylation,0.002258,0.028602,0,0,9.584184,58.398789,MAOB;RETSAT;MDH1;DLAT
3,MSigDB_Hallmark_2020,Pperoxisome,0.003280,0.031157,0,0,4.820876,27.575395,ABCD2;RETSAT;ACSL1;ELOVL5;ALB;DHCR24
4,MSigDB_Hallmark_2020,mTORC1 Signaling,0.007566,0.057501,0,0,2.699561,13.184922,ELOVL5;SCD;GBE1;ME1;ELOVL6;DHCR24;VLDLR;DHCR7;...

Doing for top 200 gene

,gene_name,p_value,tissue,snp_id,beta,qv,maf,cluster_i,gene_chr,gene_start,gene_end
1,C4B,0.000139,Adipose_Subcutaneous,chr10_17384475_A_C_b38,-0.270787,0.276953,0.769494,1,chr6,32014762,32035418
2,TPGS1,0.000430,Adipose_Subcutaneous,chr10_17384475_A_C_b38,-0.255081,0.332200,0.769494,1,chr19,507834,519654
3,HLX,0.000486,Adipose_Subcutaneous,chr10_17384475_A_C_b38,-0.250685,0.332200,0.769494,1,chr1,220879400,220885059
4,JUND,0.000568,Adipose_Subcutaneous,chr10_17384475_A_C_b38,-0.241491,0.332200,0.769494,1,chr19,18279760,18281622
5,JUN,0.000581,Adipose_Subcutaneous,chr10_17384475_A_C_b38,-0.234458,0.332200,0.769494,1,chr1,58780788,58784327

,Gene_set,Term,P-value,Adjusted P-value,Old P-value,Old adjusted P-value,Odds Ratio,Combined Score,Genes
0,MSigDB_Hallmark_2020,TNF-alpha Signaling via NF-kB,3.683206e-17,1.510114e-15,0,0,8.021243,303.525157,PTGER4;PPP1R15A;CDKN1A;CEBPD;TNFAIP3;SLC2A3;PT...
1,MSigDB_Hallmark_2020,Interferon Gamma Response,1.158668e-04,2.375270e-03,0,0,3.510334,31.814398,CD74;CDKN1A;IL4R;VCAM1;MX2;MX1;TNFAIP3;ISG15;P...
2,MSigDB_Hallmark_2020,Hypoxia,2.796254e-04,3.821548e-03,0,0,3.201395,26.194004,ERO1A;PPP1R15A;JUN;CDKN1A;TES;CDKN1B;DUSP1;STC...
3,MSigDB_Hallmark_2020,Interferon Alpha Response,6.930590e-04,7.103855e-03,0,0,4.860677,35.358487,IFIH1;CD74;IL4R;IFI27;CCRL2;MX1;IRF7;ISG15
4,MSigDB_Hallmark_2020,Inflammatory Response,2.117655e-03,1.736477e-02,0,0,2.775459,17.089740,PTGER4;CDKN1A;IL4R;CXCL8;SELE;CX3CL1;ICAM1;RGS...

Spleen
For Spleen top 50 correction type = FDR
Doing for top 50 gene

,gene_name,p_value,tissue,snp_id,beta,qv,maf,cluster_i,gene_chr,gene_start,gene_end
0,RP11-678G14.3,0.000345,Spleen,chr10_80647340_G_GGT_b38,0.429374,0.999514,0.800377,4,chr19,21570822,21587322
1,BTNL8,0.000567,Spleen,chr10_80647340_G_GGT_b38,0.406682,0.999514,0.800377,4,chr5,180899077,180950906
2,KCNH3,0.001423,Spleen,chr10_80647340_G_GGT_b38,0.370250,0.999514,0.800377,4,chr12,49539157,49558294
3,CLEC7A,0.001670,Spleen,chr10_80647340_G_GGT_b38,0.370797,0.999514,0.800377,4,chr12,10116777,10130258
6,HAL,0.005032,Spleen,chr10_80647340_G_GGT_b38,0.337432,0.999514,0.800377,4,chr12,95972662,95996365

,Gene_set,Term,P-value,Adjusted P-value,Old P-value,Old adjusted P-value,Odds Ratio,Combined Score,Genes
0,MSigDB_Hallmark_2020,Androgen Response,0.212772,0.71475,0,0,4.442857,6.875480,KRT19
1,MSigDB_Hallmark_2020,Myogenesis,0.220088,0.71475,0,0,2.356360,3.566884,ITGA7;MYOM2
2,MSigDB_Hallmark_2020,Adipogenesis,0.344452,0.71475,0,0,2.459184,2.620997,ITGA7
3,MSigDB_Hallmark_2020,IL-6/JAK/STAT3 Signaling,0.388047,0.71475,0,0,2.104956,1.992611,TLR2
4,MSigDB_Hallmark_2020,KRAS Signaling Dn,0.415518,0.71475,0,0,1.920142,1.686323,UPK3B

Doing for top 50 gene

,gene_name,p_value,tissue,snp_id,beta,qv,maf,cluster_i,gene_chr,gene_start,gene_end
4,SNHG5,0.002405,Spleen,chr10_80647340_G_GGT_b38,-0.353937,0.999514,0.800377,4,chr6,85660950,85678736
5,RP11-322E11.5,0.003401,Spleen,chr10_80647340_G_GGT_b38,-0.354299,0.999514,0.800377,4,chr18,35443869,35467088
9,SNHG9,0.006665,Spleen,chr10_80647340_G_GGT_b38,-0.318886,0.999514,0.800377,4,chr16,1964959,1965509
11,HAMP,0.007883,Spleen,chr10_80647340_G_GGT_b38,-0.319683,0.999514,0.800377,4,chr19,35280716,35285143
12,AC016739.2,0.008736,Spleen,chr10_80647340_G_GGT_b38,-0.318259,0.999514,0.800377,4,chr2,176200908,176201252

,Gene_set,Term,P-value,Adjusted P-value,Old P-value,Old adjusted P-value,Odds Ratio,Combined Score,Genes
0,MSigDB_Hallmark_2020,Myc Targets V2,0.003182,0.028636,0,0,30.480836,175.274680,NOP2;HSPE1
1,MSigDB_Hallmark_2020,Myc Targets V1,0.144905,0.514583,0,0,6.930159,13.386836,HSPE1
2,MSigDB_Hallmark_2020,Complement,0.171528,0.514583,0,0,2.800650,4.937578,ANG;HSPA1A
3,MSigDB_Hallmark_2020,Glycolysis,0.388047,0.600675,0,0,2.104956,1.992611,ANG
4,MSigDB_Hallmark_2020,mTORC1 Signaling,0.400021,0.600675,0,0,2.021475,1.852151,HSPE1

Spleen
For Spleen top 100 correction type = FDR
Doing for top 100 gene

,gene_name,p_value,tissue,snp_id,beta,qv,maf,cluster_i,gene_chr,gene_start,gene_end
0,RP11-678G14.3,0.000345,Spleen,chr10_80647340_G_GGT_b38,0.429374,0.999514,0.800377,4,chr19,21570822,21587322
1,BTNL8,0.000567,Spleen,chr10_80647340_G_GGT_b38,0.406682,0.999514,0.800377,4,chr5,180899077,180950906
2,KCNH3,0.001423,Spleen,chr10_80647340_G_GGT_b38,0.370250,0.999514,0.800377,4,chr12,49539157,49558294
3,CLEC7A,0.001670,Spleen,chr10_80647340_G_GGT_b38,0.370797,0.999514,0.800377,4,chr12,10116777,10130258
6,HAL,0.005032,Spleen,chr10_80647340_G_GGT_b38,0.337432,0.999514,0.800377,4,chr12,95972662,95996365

,Gene_set,Term,P-value,Adjusted P-value,Old P-value,Old adjusted P-value,Odds Ratio,Combined Score,Genes
0,MSigDB_Hallmark_2020,Allograft Rejection,0.075696,0.79057,0,0,2.647388,6.833005,KRT1;CFP;ELANE;TLR2
1,MSigDB_Hallmark_2020,KRAS Signaling Dn,0.287501,0.79057,0,0,1.940590,2.419000,KRT1;UPK3B
2,MSigDB_Hallmark_2020,Androgen Response,0.381978,0.79057,0,0,2.173737,2.091989,KRT19
3,MSigDB_Hallmark_2020,Estrogen Response Early,0.419099,0.79057,0,0,1.426230,1.240319,KRT19;MYB
4,MSigDB_Hallmark_2020,Apical Junction,0.426964,0.79057,0,0,1.402897,1.193942,COL17A1;CLDN9

Doing for top 100 gene

,gene_name,p_value,tissue,snp_id,beta,qv,maf,cluster_i,gene_chr,gene_start,gene_end
4,SNHG5,0.002405,Spleen,chr10_80647340_G_GGT_b38,-0.353937,0.999514,0.800377,4,chr6,85660950,85678736
5,RP11-322E11.5,0.003401,Spleen,chr10_80647340_G_GGT_b38,-0.354299,0.999514,0.800377,4,chr18,35443869,35467088
9,SNHG9,0.006665,Spleen,chr10_80647340_G_GGT_b38,-0.318886,0.999514,0.800377,4,chr16,1964959,1965509
11,HAMP,0.007883,Spleen,chr10_80647340_G_GGT_b38,-0.319683,0.999514,0.800377,4,chr19,35280716,35285143
12,AC016739.2,0.008736,Spleen,chr10_80647340_G_GGT_b38,-0.318259,0.999514,0.800377,4,chr2,176200908,176201252

,Gene_set,Term,P-value,Adjusted P-value,Old P-value,Old adjusted P-value,Odds Ratio,Combined Score,Genes
0,MSigDB_Hallmark_2020,Myc Targets V2,0.014297,0.285938,0,0,13.576138,57.667550,NOP2;HSPE1
1,MSigDB_Hallmark_2020,Hypoxia,0.080567,0.475791,0,0,2.585484,6.511985,EFNA1;CSRP2;HSPA5;ACKR3
2,MSigDB_Hallmark_2020,Glycolysis,0.086908,0.475791,0,0,3.038298,7.422260,HSPA5;ANG;FKBP4
3,MSigDB_Hallmark_2020,mTORC1 Signaling,0.095158,0.475791,0,0,2.912925,6.851824,HSPA5;CACYBP;HSPE1
4,MSigDB_Hallmark_2020,Complement,0.219472,0.658623,0,0,1.917568,2.908047,HSPA5;ANG;HSPA1A

Spleen
For Spleen top 150 correction type = FDR
Doing for top 150 gene

,gene_name,p_value,tissue,snp_id,beta,qv,maf,cluster_i,gene_chr,gene_start,gene_end
0,RP11-678G14.3,0.000345,Spleen,chr10_80647340_G_GGT_b38,0.429374,0.999514,0.800377,4,chr19,21570822,21587322
1,BTNL8,0.000567,Spleen,chr10_80647340_G_GGT_b38,0.406682,0.999514,0.800377,4,chr5,180899077,180950906
2,KCNH3,0.001423,Spleen,chr10_80647340_G_GGT_b38,0.370250,0.999514,0.800377,4,chr12,49539157,49558294
3,CLEC7A,0.001670,Spleen,chr10_80647340_G_GGT_b38,0.370797,0.999514,0.800377,4,chr12,10116777,10130258
6,HAL,0.005032,Spleen,chr10_80647340_G_GGT_b38,0.337432,0.999514,0.800377,4,chr12,95972662,95996365

,Gene_set,Term,P-value,Adjusted P-value,Old P-value,Old adjusted P-value,Odds Ratio,Combined Score,Genes
0,MSigDB_Hallmark_2020,Allograft Rejection,0.032205,0.901752,0,0,2.698077,9.269569,KRT1;PRF1;CFP;ELANE;TLR2;PF4
1,MSigDB_Hallmark_2020,KRAS Signaling Dn,0.073545,0.982041,0,0,2.695763,7.035555,TG;KRT1;UPK3B;MEFV
2,MSigDB_Hallmark_2020,Myogenesis,0.123758,0.982041,0,0,1.984412,4.146281,CFD;MYBPC3;STC2;ITGA7;MYOM2
3,MSigDB_Hallmark_2020,Reactive Oxygen Species Pathway,0.241320,0.982041,0,0,4.091083,5.816020,MPO
4,MSigDB_Hallmark_2020,Estrogen Response Early,0.360910,0.982041,0,0,1.433333,1.460748,KRT19;STC2;MYB

Doing for top 150 gene

,gene_name,p_value,tissue,snp_id,beta,qv,maf,cluster_i,gene_chr,gene_start,gene_end
4,SNHG5,0.002405,Spleen,chr10_80647340_G_GGT_b38,-0.353937,0.999514,0.800377,4,chr6,85660950,85678736
5,RP11-322E11.5,0.003401,Spleen,chr10_80647340_G_GGT_b38,-0.354299,0.999514,0.800377,4,chr18,35443869,35467088
9,SNHG9,0.006665,Spleen,chr10_80647340_G_GGT_b38,-0.318886,0.999514,0.800377,4,chr16,1964959,1965509
11,HAMP,0.007883,Spleen,chr10_80647340_G_GGT_b38,-0.319683,0.999514,0.800377,4,chr19,35280716,35285143
12,AC016739.2,0.008736,Spleen,chr10_80647340_G_GGT_b38,-0.318259,0.999514,0.800377,4,chr2,176200908,176201252

,Gene_set,Term,P-value,Adjusted P-value,Old P-value,Old adjusted P-value,Odds Ratio,Combined Score,Genes
0,MSigDB_Hallmark_2020,Myc Targets V2,0.002407,0.050890,0,0,15.267857,92.052670,NOP2;HSPE1;HSPD1
1,MSigDB_Hallmark_2020,Hypoxia,0.003393,0.050890,0,0,3.564868,20.270359,EFNA1;IL6;CSRP2;HSPA5;ACKR3;ALDOB;CP;IER3
2,MSigDB_Hallmark_2020,Myc Targets V1,0.013595,0.108288,0,0,7.035165,30.237386,HSPE1;NME1;HSPD1
3,MSigDB_Hallmark_2020,Unfolded Protein Response,0.018899,0.108288,0,0,6.094286,24.186034,HSPA5;MTHFD2;HYOU1
4,MSigDB_Hallmark_2020,Glycolysis,0.021678,0.108288,0,0,3.410628,13.067658,HSPA5;ANG;ALDOB;FKBP4;IER3

Spleen
For Spleen top 200 correction type = FDR
Doing for top 200 gene

,gene_name,p_value,tissue,snp_id,beta,qv,maf,cluster_i,gene_chr,gene_start,gene_end
0,RP11-678G14.3,0.000345,Spleen,chr10_80647340_G_GGT_b38,0.429374,0.999514,0.800377,4,chr19,21570822,21587322
1,BTNL8,0.000567,Spleen,chr10_80647340_G_GGT_b38,0.406682,0.999514,0.800377,4,chr5,180899077,180950906
2,KCNH3,0.001423,Spleen,chr10_80647340_G_GGT_b38,0.370250,0.999514,0.800377,4,chr12,49539157,49558294
3,CLEC7A,0.001670,Spleen,chr10_80647340_G_GGT_b38,0.370797,0.999514,0.800377,4,chr12,10116777,10130258
6,HAL,0.005032,Spleen,chr10_80647340_G_GGT_b38,0.337432,0.999514,0.800377,4,chr12,95972662,95996365

,Gene_set,Term,P-value,Adjusted P-value,Old P-value,Old adjusted P-value,Odds Ratio,Combined Score,Genes
0,MSigDB_Hallmark_2020,Allograft Rejection,0.029939,0.898164,0,0,2.521064,8.845403,KRT1;PRF1;CFP;ELANE;CCR2;TLR2;PF4
1,MSigDB_Hallmark_2020,KRAS Signaling Dn,0.137384,0.967208,0,0,2.119818,4.207786,TG;KRT1;MEFV;UPK3B
2,MSigDB_Hallmark_2020,Myogenesis,0.236090,0.967208,0,0,1.558126,2.249223,CFD;MYBPC3;STC2;ITGA7;MYOM2
3,MSigDB_Hallmark_2020,Reactive Oxygen Species Pathway,0.293675,0.967208,0,0,3.230710,3.958534,MPO
4,MSigDB_Hallmark_2020,Bile Acid Metabolism,0.366636,0.967208,0,0,1.615975,1.621445,PIPOX;GNMT

Doing for top 200 gene

,gene_name,p_value,tissue,snp_id,beta,qv,maf,cluster_i,gene_chr,gene_start,gene_end
4,SNHG5,0.002405,Spleen,chr10_80647340_G_GGT_b38,-0.353937,0.999514,0.800377,4,chr6,85660950,85678736
5,RP11-322E11.5,0.003401,Spleen,chr10_80647340_G_GGT_b38,-0.354299,0.999514,0.800377,4,chr18,35443869,35467088
9,SNHG9,0.006665,Spleen,chr10_80647340_G_GGT_b38,-0.318886,0.999514,0.800377,4,chr16,1964959,1965509
11,HAMP,0.007883,Spleen,chr10_80647340_G_GGT_b38,-0.319683,0.999514,0.800377,4,chr19,35280716,35285143
12,AC016739.2,0.008736,Spleen,chr10_80647340_G_GGT_b38,-0.318259,0.999514,0.800377,4,chr2,176200908,176201252

,Gene_set,Term,P-value,Adjusted P-value,Old P-value,Old adjusted P-value,Odds Ratio,Combined Score,Genes
0,MSigDB_Hallmark_2020,Myc Targets V2,0.005651,0.115737,0,0,11.118421,57.549033,NOP2;HSPE1;HSPD1
1,MSigDB_Hallmark_2020,mTORC1 Signaling,0.006808,0.115737,0,0,3.500836,17.467953,STIP1;SDF2L1;HSPA5;MTHFD2;CACYBP;HSPE1;HSPD1
2,MSigDB_Hallmark_2020,Hypoxia,0.019419,0.174088,0,0,2.570502,10.131694,EFNA1;IL6;CSRP2;HSPA5;ACKR3;ALDOB;CP;IER3
3,MSigDB_Hallmark_2020,UV Response Up,0.020481,0.174088,0,0,3.053233,11.871766,STIP1;DNAJB1;IL6;APOM;FKBP4;CXCL2
4,MSigDB_Hallmark_2020,Myc Targets V1,0.030083,0.199799,0,0,5.123077,17.950148,HSPE1;NME1;HSPD1

Thyroid
Spleen
Skin_Sun_Exposed_Lower_leg
Esophagus_Mucosa
Adipose_Subcutaneous
Thyroid
For Thyroid top 50 correction type = Bonferroni
Doing for top 50 gene

,gene_name,p_value,tissue,snp_id,beta,qv,maf,cluster_i,gene_chr,gene_start,gene_end
1,CENPJ,8.820354e-31,Thyroid,chr9_97772921_C_G_b38,0.693229,1.868592e-27,0.668831,2,chr13,24882284,24922889
4,TPTE2P1,1.870313e-27,Thyroid,chr9_97772921_C_G_b38,0.654771,1.584903e-24,0.668831,2,chr13,24924677,24968487
6,CPAMD8,1.325091e-19,Thyroid,chr9_97772921_C_G_b38,0.511589,8.020586e-17,0.668831,2,chr19,16892947,17026815
7,DTX4,3.129176e-19,Thyroid,chr9_97772921_C_G_b38,0.543535,1.657290e-16,0.668831,2,chr11,59171430,59208509
10,RP11-756A22.7,5.134648e-18,Thyroid,chr9_97772921_C_G_b38,0.533252,1.977773e-15,0.668831,2,chr13,24933006,24936796

,Gene_set,Term,P-value,Adjusted P-value,Old P-value,Old adjusted P-value,Odds Ratio,Combined Score,Genes
0,MSigDB_Hallmark_2020,Hedgehog Signaling,0.008395,0.124047,0,0,17.358333,82.974162,CELSR1;NKX6-1
1,MSigDB_Hallmark_2020,Pancreas Beta Cells,0.013058,0.124047,0,0,13.342949,57.886840,NKX6-1;FOXA2
2,MSigDB_Hallmark_2020,Bile Acid Metabolism,0.039897,0.252680,0,0,6.918333,22.287129,SULT2B1;HSD17B6
3,MSigDB_Hallmark_2020,Estrogen Response Early,0.054382,0.258316,0,0,3.744073,10.901684,SULT2B1;MUC1;CELSR1
4,MSigDB_Hallmark_2020,Myc Targets V2,0.090896,0.345404,0,0,12.154519,29.147031,SLC19A1

Doing for top 50 gene

,gene_name,p_value,tissue,snp_id,beta,qv,maf,cluster_i,gene_chr,gene_start,gene_end
0,FAM163A,4.537380e-31,Thyroid,chr9_97772921_C_G_b38,-0.694002,1.868592e-27,0.668831,2,chr1,179743163,179816183
2,IGHE,1.957715e-30,Thyroid,chr9_97772921_C_G_b38,-0.650482,2.764947e-27,0.668831,2,chr14,105599941,105601728
3,FAM189A1,6.623082e-28,Thyroid,chr9_97772921_C_G_b38,-0.665878,7.015500e-25,0.668831,2,chr15,29120254,29570723
5,PLA2G4F,4.443909e-21,Thyroid,chr9_97772921_C_G_b38,-0.577363,3.138141e-18,0.668831,2,chr15,42139034,42156636
8,HK2,8.583262e-19,Thyroid,chr9_97772921_C_G_b38,-0.541636,4.040809e-16,0.668831,2,chr2,74833988,74893359

,Gene_set,Term,P-value,Adjusted P-value,Old P-value,Old adjusted P-value,Odds Ratio,Combined Score,Genes
0,MSigDB_Hallmark_2020,Myc Targets V2,0.090896,0.742396,0,0,12.154519,29.147031,HK2
1,MSigDB_Hallmark_2020,Myogenesis,0.131940,0.742396,0,0,2.499182,5.061855,ACHE;NCAM1;PVALB
2,MSigDB_Hallmark_2020,Hedgehog Signaling,0.133256,0.742396,0,0,7.727273,15.574182,ACHE
3,MSigDB_Hallmark_2020,Apical Surface,0.183494,0.742396,0,0,5.306122,8.996920,MAL
4,MSigDB_Hallmark_2020,Pperoxisome,0.212255,0.742396,0,0,4.465091,6.920744,DIO1

Thyroid
For Thyroid top 100 correction type = Bonferroni
Doing for top 100 gene

,gene_name,p_value,tissue,snp_id,beta,qv,maf,cluster_i,gene_chr,gene_start,gene_end
1,CENPJ,8.820354e-31,Thyroid,chr9_97772921_C_G_b38,0.693229,1.868592e-27,0.668831,2,chr13,24882284,24922889
4,TPTE2P1,1.870313e-27,Thyroid,chr9_97772921_C_G_b38,0.654771,1.584903e-24,0.668831,2,chr13,24924677,24968487
6,CPAMD8,1.325091e-19,Thyroid,chr9_97772921_C_G_b38,0.511589,8.020586e-17,0.668831,2,chr19,16892947,17026815
7,DTX4,3.129176e-19,Thyroid,chr9_97772921_C_G_b38,0.543535,1.657290e-16,0.668831,2,chr11,59171430,59208509
10,RP11-756A22.7,5.134648e-18,Thyroid,chr9_97772921_C_G_b38,0.533252,1.977773e-15,0.668831,2,chr13,24933006,24936796

,Gene_set,Term,P-value,Adjusted P-value,Old P-value,Old adjusted P-value,Odds Ratio,Combined Score,Genes
0,MSigDB_Hallmark_2020,Pancreas Beta Cells,0.004757,0.118923,0,0,10.603093,56.706983,PCSK2;NKX6-1;FOXA2
1,MSigDB_Hallmark_2020,Estrogen Response Early,0.028344,0.261274,0,0,3.140867,11.191965,SULT2B1;MUC1;MLPH;RHOBTB3;CELSR1
2,MSigDB_Hallmark_2020,Hedgehog Signaling,0.031353,0.261274,0,0,8.400000,29.084583,CELSR1;NKX6-1
3,MSigDB_Hallmark_2020,Estrogen Response Late,0.115982,0.664791,0,0,2.250556,4.848412,SULT2B1;ISG20;MDK;TNNC1
4,MSigDB_Hallmark_2020,Bile Acid Metabolism,0.132958,0.664791,0,0,3.347755,6.754835,SULT2B1;HSD17B6

Doing for top 100 gene

,gene_name,p_value,tissue,snp_id,beta,qv,maf,cluster_i,gene_chr,gene_start,gene_end
0,FAM163A,4.537380e-31,Thyroid,chr9_97772921_C_G_b38,-0.694002,1.868592e-27,0.668831,2,chr1,179743163,179816183
2,IGHE,1.957715e-30,Thyroid,chr9_97772921_C_G_b38,-0.650482,2.764947e-27,0.668831,2,chr14,105599941,105601728
3,FAM189A1,6.623082e-28,Thyroid,chr9_97772921_C_G_b38,-0.665878,7.015500e-25,0.668831,2,chr15,29120254,29570723
5,PLA2G4F,4.443909e-21,Thyroid,chr9_97772921_C_G_b38,-0.577363,3.138141e-18,0.668831,2,chr15,42139034,42156636
8,HK2,8.583262e-19,Thyroid,chr9_97772921_C_G_b38,-0.541636,4.040809e-16,0.668831,2,chr2,74833988,74893359

,Gene_set,Term,P-value,Adjusted P-value,Old P-value,Old adjusted P-value,Odds Ratio,Combined Score,Genes
0,MSigDB_Hallmark_2020,UV Response Up,0.033584,0.877524,0,0,3.539931,12.013506,PTPRD;CA2;CEBPG;ENO2
1,MSigDB_Hallmark_2020,IL-2/STAT5 Signaling,0.104338,0.877524,0,0,2.346065,5.302379,CA2;SPRY4;PHLDA1;HK2
2,MSigDB_Hallmark_2020,Myogenesis,0.108116,0.877524,0,0,2.076367,4.618978,ACHE;NCAM1;TPD52L1;CRYAB;PVALB
3,MSigDB_Hallmark_2020,Glycolysis,0.113682,0.877524,0,0,2.684141,5.836261,G6PD;ENO2;HK2
4,MSigDB_Hallmark_2020,Bile Acid Metabolism,0.132958,0.877524,0,0,3.347755,6.754835,DIO1;RBP1

Thyroid
For Thyroid top 150 correction type = Bonferroni
Doing for top 150 gene

,gene_name,p_value,tissue,snp_id,beta,qv,maf,cluster_i,gene_chr,gene_start,gene_end
1,CENPJ,8.820354e-31,Thyroid,chr9_97772921_C_G_b38,0.693229,1.868592e-27,0.668831,2,chr13,24882284,24922889
4,TPTE2P1,1.870313e-27,Thyroid,chr9_97772921_C_G_b38,0.654771,1.584903e-24,0.668831,2,chr13,24924677,24968487
6,CPAMD8,1.325091e-19,Thyroid,chr9_97772921_C_G_b38,0.511589,8.020586e-17,0.668831,2,chr19,16892947,17026815
7,DTX4,3.129176e-19,Thyroid,chr9_97772921_C_G_b38,0.543535,1.657290e-16,0.668831,2,chr11,59171430,59208509
10,RP11-756A22.7,5.134648e-18,Thyroid,chr9_97772921_C_G_b38,0.533252,1.977773e-15,0.668831,2,chr13,24933006,24936796

,Gene_set,Term,P-value,Adjusted P-value,Old P-value,Old adjusted P-value,Odds Ratio,Combined Score,Genes
0,MSigDB_Hallmark_2020,Estrogen Response Early,0.003970,0.134987,0,0,3.476490,19.221292,SULT2B1;MUC1;MLPH;TMPRSS3;RHOBTB3;TFF3;INHBB;C...
1,MSigDB_Hallmark_2020,Pancreas Beta Cells,0.014570,0.239199,0,0,6.911565,29.227543,PCSK2;NKX6-1;FOXA2
2,MSigDB_Hallmark_2020,Estrogen Response Late,0.021106,0.239199,0,0,2.722222,10.502902,SULT2B1;ISG20;MDK;TNNC1;DLG5;TMPRSS3;TFF3
3,MSigDB_Hallmark_2020,Hedgehog Signaling,0.065426,0.468150,0,0,5.494595,14.982864,CELSR1;NKX6-1
4,MSigDB_Hallmark_2020,Bile Acid Metabolism,0.068846,0.468150,0,0,3.445578,9.219983,SULT2B1;DHCR24;HSD17B6

Doing for top 150 gene

,gene_name,p_value,tissue,snp_id,beta,qv,maf,cluster_i,gene_chr,gene_start,gene_end
0,FAM163A,4.537380e-31,Thyroid,chr9_97772921_C_G_b38,-0.694002,1.868592e-27,0.668831,2,chr1,179743163,179816183
2,IGHE,1.957715e-30,Thyroid,chr9_97772921_C_G_b38,-0.650482,2.764947e-27,0.668831,2,chr14,105599941,105601728
3,FAM189A1,6.623082e-28,Thyroid,chr9_97772921_C_G_b38,-0.665878,7.015500e-25,0.668831,2,chr15,29120254,29570723
5,PLA2G4F,4.443909e-21,Thyroid,chr9_97772921_C_G_b38,-0.577363,3.138141e-18,0.668831,2,chr15,42139034,42156636
8,HK2,8.583262e-19,Thyroid,chr9_97772921_C_G_b38,-0.541636,4.040809e-16,0.668831,2,chr2,74833988,74893359

,Gene_set,Term,P-value,Adjusted P-value,Old P-value,Old adjusted P-value,Odds Ratio,Combined Score,Genes
0,MSigDB_Hallmark_2020,Glycolysis,0.030922,0.461528,0,0,3.088889,10.737912,G6PD;GCLC;CHST1;ENO2;HK2
1,MSigDB_Hallmark_2020,KRAS Signaling Dn,0.034529,0.461528,0,0,2.654101,8.933558,EPHA5;ATP4A;CD80;IGFBP2;YBX2;SLC6A3
2,MSigDB_Hallmark_2020,UV Response Up,0.035864,0.461528,0,0,2.955979,9.837568,PTPRD;CA2;CEBPG;IGFBP2;ENO2
3,MSigDB_Hallmark_2020,Spermatogenesis,0.046153,0.461528,0,0,4.138776,12.730039,CCNB2;YBX2;ACRBP
4,MSigDB_Hallmark_2020,Hedgehog Signaling,0.065426,0.523407,0,0,5.494595,14.982864,ACHE;NRCAM

Thyroid
For Thyroid top 200 correction type = Bonferroni
Doing for top 200 gene

,gene_name,p_value,tissue,snp_id,beta,qv,maf,cluster_i,gene_chr,gene_start,gene_end
1,CENPJ,8.820354e-31,Thyroid,chr9_97772921_C_G_b38,0.693229,1.868592e-27,0.668831,2,chr13,24882284,24922889
4,TPTE2P1,1.870313e-27,Thyroid,chr9_97772921_C_G_b38,0.654771,1.584903e-24,0.668831,2,chr13,24924677,24968487
6,CPAMD8,1.325091e-19,Thyroid,chr9_97772921_C_G_b38,0.511589,8.020586e-17,0.668831,2,chr19,16892947,17026815
7,DTX4,3.129176e-19,Thyroid,chr9_97772921_C_G_b38,0.543535,1.657290e-16,0.668831,2,chr11,59171430,59208509
10,RP11-756A22.7,5.134648e-18,Thyroid,chr9_97772921_C_G_b38,0.533252,1.977773e-15,0.668831,2,chr13,24933006,24936796

,Gene_set,Term,P-value,Adjusted P-value,Old P-value,Old adjusted P-value,Odds Ratio,Combined Score,Genes
0,MSigDB_Hallmark_2020,Estrogen Response Early,0.006940,0.249857,0,0,2.917048,14.498856,SULT2B1;MUC1;MLPH;ELF3;TMPRSS3;TFF3;RHOBTB3;IN...
1,MSigDB_Hallmark_2020,Glycolysis,0.029174,0.261765,0,0,2.798969,9.892876,ISG20;ELF3;CITED2;TFF3;SOX9;CACNA1H
2,MSigDB_Hallmark_2020,Pancreas Beta Cells,0.031179,0.261765,0,0,5.093909,17.665698,PCSK2;NKX6-1;FOXA2
3,MSigDB_Hallmark_2020,Estrogen Response Late,0.031931,0.261765,0,0,2.321009,7.993989,SULT2B1;ISG20;ST6GALNAC2;MDK;TNNC1;TMPRSS3;DLG...
4,MSigDB_Hallmark_2020,Bile Acid Metabolism,0.036356,0.261765,0,0,3.551908,11.772409,SULT2B1;BBOX1;DHCR24;HSD17B6

Doing for top 200 gene

,gene_name,p_value,tissue,snp_id,beta,qv,maf,cluster_i,gene_chr,gene_start,gene_end
0,FAM163A,4.537380e-31,Thyroid,chr9_97772921_C_G_b38,-0.694002,1.868592e-27,0.668831,2,chr1,179743163,179816183
2,IGHE,1.957715e-30,Thyroid,chr9_97772921_C_G_b38,-0.650482,2.764947e-27,0.668831,2,chr14,105599941,105601728
3,FAM189A1,6.623082e-28,Thyroid,chr9_97772921_C_G_b38,-0.665878,7.015500e-25,0.668831,2,chr15,29120254,29570723
5,PLA2G4F,4.443909e-21,Thyroid,chr9_97772921_C_G_b38,-0.577363,3.138141e-18,0.668831,2,chr15,42139034,42156636
8,HK2,8.583262e-19,Thyroid,chr9_97772921_C_G_b38,-0.541636,4.040809e-16,0.668831,2,chr2,74833988,74893359

,Gene_set,Term,P-value,Adjusted P-value,Old P-value,Old adjusted P-value,Odds Ratio,Combined Score,Genes
0,MSigDB_Hallmark_2020,Spermatogenesis,0.003779,0.158717,0,0,5.709402,31.848755,CCNB2;GSTM3;HSPA4L;YBX2;ACRBP
1,MSigDB_Hallmark_2020,KRAS Signaling Dn,0.043096,0.565488,0,0,2.318904,7.291388,EPHA5;ATP4A;TGFB2;CD80;IGFBP2;YBX2;SLC6A3
2,MSigDB_Hallmark_2020,Estrogen Response Early,0.055655,0.565488,0,0,2.176166,6.286051,CYP26B1;DEPTOR;ZNF185;PODXL;MYOF;ABAT;TPD52L1
3,MSigDB_Hallmark_2020,DNA Repair,0.078085,0.565488,0,0,5.073232,12.936547,CETN2;CCNO
4,MSigDB_Hallmark_2020,Xenobiotic Metabolism,0.080373,0.565488,0,0,2.115891,5.334330,TGFB2;GCLC;ARG1;CA2;RAP1GAP;CYP17A1

Esophagus_Mucosa
For Esophagus_Mucosa top 50 correction type = Bonferroni
Doing for top 50 gene

,gene_name,p_value,tissue,snp_id,beta,qv,maf,cluster_i,gene_chr,gene_start,gene_end
1,LAPTM4B,8.528937e-07,Esophagus_Mucosa,chr1_78663229_G_A_b38,0.314870,0.000697,0.547222,7,chr8,97775057,97853013
3,RANBP1,1.015402e-06,Esophagus_Mucosa,chr1_78663229_G_A_b38,0.314146,0.000697,0.547222,7,chr22,20115938,20127357
4,SAA1,1.125504e-06,Esophagus_Mucosa,chr1_78663229_G_A_b38,0.310825,0.000697,0.547222,7,chr11,18266174,18269977
9,IFI16,1.938679e-06,Esophagus_Mucosa,chr1_78663229_G_A_b38,0.307319,0.000759,0.547222,7,chr1,158999968,159055155
11,SLC43A3,2.615278e-06,Esophagus_Mucosa,chr1_78663229_G_A_b38,0.299144,0.000831,0.547222,7,chr11,57406954,57427580

,Gene_set,Term,P-value,Adjusted P-value,Old P-value,Old adjusted P-value,Odds Ratio,Combined Score,Genes
0,MSigDB_Hallmark_2020,E2F Targets,9.718127e-16,2.623894e-14,0,0,37.168056,1284.801875,RANBP1;DNMT1;SPAG5;BUB1B;PAICS;LMNB1;MELK;KIF1...
1,MSigDB_Hallmark_2020,Myc Targets V1,2.043786e-07,2.759112e-06,0,0,32.786932,505.026667,RANBP1;RFC4;MCM6;KPNA2;RRP9;HSPD1
2,MSigDB_Hallmark_2020,G2-M Checkpoint,4.590948e-06,4.131853e-05,0,0,12.938469,159.032210,UBE2C;TROAP;MCM3;TACC3;MCM6;KPNA2;LMNB1
3,MSigDB_Hallmark_2020,DNA Repair,3.014818e-04,2.035002e-03,0,0,30.757979,249.348815,RFC4;ADA;ZWINT
4,MSigDB_Hallmark_2020,Myc Targets V2,9.733132e-03,5.255892e-02,0,0,16.054167,74.366424,RRP9;HSPD1

Doing for top 50 gene

,gene_name,p_value,tissue,snp_id,beta,qv,maf,cluster_i,gene_chr,gene_start,gene_end
0,SLC24A3,4.151806e-07,Esophagus_Mucosa,chr1_78663229_G_A_b38,-0.323393,0.000697,0.547222,7,chr20,19212646,19722937
2,CRISP3,9.577293e-07,Esophagus_Mucosa,chr1_78663229_G_A_b38,-0.314357,0.000697,0.547222,7,chr6,49727384,49744437
5,UPK3B,1.128828e-06,Esophagus_Mucosa,chr1_78663229_G_A_b38,-0.312264,0.000697,0.547222,7,chr7,76510428,76516521
6,CAMK2N1,1.279904e-06,Esophagus_Mucosa,chr1_78663229_G_A_b38,-0.311924,0.000697,0.547222,7,chr1,20482391,20486220
7,CALB2,1.424056e-06,Esophagus_Mucosa,chr1_78663229_G_A_b38,-0.309081,0.000697,0.547222,7,chr16,71358713,71390438

,Gene_set,Term,P-value,Adjusted P-value,Old P-value,Old adjusted P-value,Odds Ratio,Combined Score,Genes
0,MSigDB_Hallmark_2020,IL-2/STAT5 Signaling,0.019076,0.400590,0,0,4.275551,16.928355,MAFF;ST3GAL4;SH3BGRL2;MXD1
1,MSigDB_Hallmark_2020,p53 Pathway,0.065446,0.422826,0,0,3.458663,9.430137,PMM1;MXD1;ZNF365
2,MSigDB_Hallmark_2020,Fatty Acid Metabolism,0.084086,0.422826,0,0,4.429398,10.966827,HPGD;MGLL
3,MSigDB_Hallmark_2020,Notch Signaling,0.109401,0.422826,0,0,9.834184,21.760428,DTX2
4,MSigDB_Hallmark_2020,Adipogenesis,0.116190,0.422826,0,0,3.616477,7.784564,CCNG2;MGLL

Esophagus_Mucosa
For Esophagus_Mucosa top 100 correction type = Bonferroni
Doing for top 100 gene

,gene_name,p_value,tissue,snp_id,beta,qv,maf,cluster_i,gene_chr,gene_start,gene_end
1,LAPTM4B,8.528937e-07,Esophagus_Mucosa,chr1_78663229_G_A_b38,0.314870,0.000697,0.547222,7,chr8,97775057,97853013
3,RANBP1,1.015402e-06,Esophagus_Mucosa,chr1_78663229_G_A_b38,0.314146,0.000697,0.547222,7,chr22,20115938,20127357
4,SAA1,1.125504e-06,Esophagus_Mucosa,chr1_78663229_G_A_b38,0.310825,0.000697,0.547222,7,chr11,18266174,18269977
9,IFI16,1.938679e-06,Esophagus_Mucosa,chr1_78663229_G_A_b38,0.307319,0.000759,0.547222,7,chr1,158999968,159055155
11,SLC43A3,2.615278e-06,Esophagus_Mucosa,chr1_78663229_G_A_b38,0.299144,0.000831,0.547222,7,chr11,57406954,57427580

,Gene_set,Term,P-value,Adjusted P-value,Old P-value,Old adjusted P-value,Odds Ratio,Combined Score,Genes
0,MSigDB_Hallmark_2020,E2F Targets,5.044279e-32,1.765497e-30,0,0,56.643162,4081.959383,DNMT1;RNASEH2A;TFRC;HMGB2;BUB1B;AURKB;LMNB1;PT...
1,MSigDB_Hallmark_2020,G2-M Checkpoint,6.511218e-15,1.139463e-13,0,0,20.347178,664.645661,UBE2C;TROAP;PLK1;CDC6;AURKB;LMNB1;CCNA2;CDC45;...
2,MSigDB_Hallmark_2020,Myc Targets V1,9.730203e-13,1.135190e-11,0,0,42.719101,1181.540767,CCNA2;RANBP1;CCT2;RFC4;CDC45;MCM6;DEK;KPNA2;RR...
3,MSigDB_Hallmark_2020,Myc Targets V2,1.956984e-07,1.712361e-06,0,0,40.500000,625.590987,PLK1;TMEM97;IPO4;RRP9;SRM;HSPD1
4,MSigDB_Hallmark_2020,DNA Repair,1.154911e-04,8.084379e-04,0,0,22.654762,205.395249,FEN1;RFC4;ADA;ZWINT

Doing for top 100 gene

,gene_name,p_value,tissue,snp_id,beta,qv,maf,cluster_i,gene_chr,gene_start,gene_end
0,SLC24A3,4.151806e-07,Esophagus_Mucosa,chr1_78663229_G_A_b38,-0.323393,0.000697,0.547222,7,chr20,19212646,19722937
2,CRISP3,9.577293e-07,Esophagus_Mucosa,chr1_78663229_G_A_b38,-0.314357,0.000697,0.547222,7,chr6,49727384,49744437
5,UPK3B,1.128828e-06,Esophagus_Mucosa,chr1_78663229_G_A_b38,-0.312264,0.000697,0.547222,7,chr7,76510428,76516521
6,CAMK2N1,1.279904e-06,Esophagus_Mucosa,chr1_78663229_G_A_b38,-0.311924,0.000697,0.547222,7,chr1,20482391,20486220
7,CALB2,1.424056e-06,Esophagus_Mucosa,chr1_78663229_G_A_b38,-0.309081,0.000697,0.547222,7,chr16,71358713,71390438

,Gene_set,Term,P-value,Adjusted P-value,Old P-value,Old adjusted P-value,Odds Ratio,Combined Score,Genes
0,MSigDB_Hallmark_2020,Fatty Acid Metabolism,0.015229,0.223873,0,0,4.631127,19.379105,HPGD;TP53INP2;CIDEA;MGLL
1,MSigDB_Hallmark_2020,IL-2/STAT5 Signaling,0.016583,0.223873,0,0,3.181277,13.041218,MAFF;ST3GAL4;SH3BGRL2;EMP1;SNX9;MXD1
2,MSigDB_Hallmark_2020,Adipogenesis,0.111879,0.880653,0,0,2.711580,5.939280,CCNG2;CIDEA;MGLL
3,MSigDB_Hallmark_2020,Glycolysis,0.197028,0.880653,0,0,2.037982,3.310520,GYS2;B3GNT3;QSOX1
4,MSigDB_Hallmark_2020,Notch Signaling,0.208032,0.880653,0,0,4.804293,7.543056,DTX2

Esophagus_Mucosa
For Esophagus_Mucosa top 150 correction type = Bonferroni
Doing for top 150 gene

,gene_name,p_value,tissue,snp_id,beta,qv,maf,cluster_i,gene_chr,gene_start,gene_end
1,LAPTM4B,8.528937e-07,Esophagus_Mucosa,chr1_78663229_G_A_b38,0.314870,0.000697,0.547222,7,chr8,97775057,97853013
3,RANBP1,1.015402e-06,Esophagus_Mucosa,chr1_78663229_G_A_b38,0.314146,0.000697,0.547222,7,chr22,20115938,20127357
4,SAA1,1.125504e-06,Esophagus_Mucosa,chr1_78663229_G_A_b38,0.310825,0.000697,0.547222,7,chr11,18266174,18269977
9,IFI16,1.938679e-06,Esophagus_Mucosa,chr1_78663229_G_A_b38,0.307319,0.000759,0.547222,7,chr1,158999968,159055155
11,SLC43A3,2.615278e-06,Esophagus_Mucosa,chr1_78663229_G_A_b38,0.299144,0.000831,0.547222,7,chr11,57406954,57427580

,Gene_set,Term,P-value,Adjusted P-value,Old P-value,Old adjusted P-value,Odds Ratio,Combined Score,Genes
0,MSigDB_Hallmark_2020,E2F Targets,4.488263e-42,1.750423e-40,0,0,74.178075,7062.279989,DNMT1;RNASEH2A;TFRC;HMGB2;BUB1B;MKI67;AURKB;LM...
1,MSigDB_Hallmark_2020,G2-M Checkpoint,4.388005e-28,8.556610e-27,0,0,35.352021,2226.947805,TROAP;MKI67;AURKB;LMNB1;CCNB2;CDC45;PTTG1;NUSA...
2,MSigDB_Hallmark_2020,Myc Targets V1,1.486220e-15,1.932085e-14,0,0,49.447368,1688.258787,RANBP1;CCT2;RFC4;DDX21;DEK;RRP9;HSPD1;SRM;CCNA...
3,MSigDB_Hallmark_2020,Myc Targets V2,6.201874e-08,6.046827e-07,0,0,37.610000,624.169136,PLK1;MCM5;TMEM97;IPO4;RRP9;SRM;HSPD1
4,MSigDB_Hallmark_2020,Mitotic Spindle,1.310578e-07,1.022251e-06,0,0,10.422667,165.174551,CCNB2;CENPF;PRC1;PLK1;CDK1;NUSAP1;BIRC5;KIF2C;...

Doing for top 150 gene

,gene_name,p_value,tissue,snp_id,beta,qv,maf,cluster_i,gene_chr,gene_start,gene_end
0,SLC24A3,4.151806e-07,Esophagus_Mucosa,chr1_78663229_G_A_b38,-0.323393,0.000697,0.547222,7,chr20,19212646,19722937
2,CRISP3,9.577293e-07,Esophagus_Mucosa,chr1_78663229_G_A_b38,-0.314357,0.000697,0.547222,7,chr6,49727384,49744437
5,UPK3B,1.128828e-06,Esophagus_Mucosa,chr1_78663229_G_A_b38,-0.312264,0.000697,0.547222,7,chr7,76510428,76516521
6,CAMK2N1,1.279904e-06,Esophagus_Mucosa,chr1_78663229_G_A_b38,-0.311924,0.000697,0.547222,7,chr1,20482391,20486220
7,CALB2,1.424056e-06,Esophagus_Mucosa,chr1_78663229_G_A_b38,-0.309081,0.000697,0.547222,7,chr16,71358713,71390438

,Gene_set,Term,P-value,Adjusted P-value,Old P-value,Old adjusted P-value,Odds Ratio,Combined Score,Genes
0,MSigDB_Hallmark_2020,Adipogenesis,0.007566,0.185768,0,0,3.878125,18.941048,RIOK3;CCNG2;CIDEA;SNCG;TOB1;MGLL
1,MSigDB_Hallmark_2020,IL-2/STAT5 Signaling,0.011610,0.185768,0,0,2.847772,12.689236,ECM1;MAFF;ST3GAL4;SH3BGRL2;EMP1;SNX9;MXD1;HOPX
2,MSigDB_Hallmark_2020,Fatty Acid Metabolism,0.055788,0.595068,0,0,3.004835,8.672562,HPGD;TP53INP2;CIDEA;MGLL
3,MSigDB_Hallmark_2020,Estrogen Response Early,0.134714,0.793344,0,0,1.931557,3.872003,CALB2;SLC24A3;TIPARP;ALDH3B1;TOB1
4,MSigDB_Hallmark_2020,p53 Pathway,0.146534,0.793344,0,0,1.873732,3.598494,PLK3;PMM1;MXD1;TOB1;ZNF365

Esophagus_Mucosa
For Esophagus_Mucosa top 200 correction type = Bonferroni
Doing for top 200 gene

,gene_name,p_value,tissue,snp_id,beta,qv,maf,cluster_i,gene_chr,gene_start,gene_end
1,LAPTM4B,8.528937e-07,Esophagus_Mucosa,chr1_78663229_G_A_b38,0.314870,0.000697,0.547222,7,chr8,97775057,97853013
3,RANBP1,1.015402e-06,Esophagus_Mucosa,chr1_78663229_G_A_b38,0.314146,0.000697,0.547222,7,chr22,20115938,20127357
4,SAA1,1.125504e-06,Esophagus_Mucosa,chr1_78663229_G_A_b38,0.310825,0.000697,0.547222,7,chr11,18266174,18269977
9,IFI16,1.938679e-06,Esophagus_Mucosa,chr1_78663229_G_A_b38,0.307319,0.000759,0.547222,7,chr1,158999968,159055155
11,SLC43A3,2.615278e-06,Esophagus_Mucosa,chr1_78663229_G_A_b38,0.299144,0.000831,0.547222,7,chr11,57406954,57427580

,Gene_set,Term,P-value,Adjusted P-value,Old P-value,Old adjusted P-value,Odds Ratio,Combined Score,Genes
0,MSigDB_Hallmark_2020,E2F Targets,5.509070e-44,2.258719e-42,0,0,74.863412,7456.945969,TOP2A;DNMT1;RNASEH2A;TFRC;HMGB2;BUB1B;MKI67;AU...
1,MSigDB_Hallmark_2020,G2-M Checkpoint,1.440947e-31,2.953941e-30,0,0,36.701724,2606.366940,TOP2A;TROAP;KIF11;MKI67;AURKB;LMNB1;CDC20;CCNB...
2,MSigDB_Hallmark_2020,Myc Targets V1,1.232839e-20,1.684880e-19,0,0,93.318436,4277.939378,CCT2;RANBP1;RFC4;DDX21;DEK;TYMS;RRP9;HSPD1;SRM...
3,MSigDB_Hallmark_2020,Mitotic Spindle,2.017198e-11,2.067628e-10,0,0,13.598527,334.887200,TOP2A;PLK1;KIF23;KIF11;NDC80;LMNB1;TPX2;CCNB2;...
4,MSigDB_Hallmark_2020,Myc Targets V2,1.494238e-08,1.225275e-07,0,0,39.280423,707.796487,PLK1;MCM4;MCM5;TMEM97;IPO4;RRP9;SRM;HSPD1

Doing for top 200 gene

,gene_name,p_value,tissue,snp_id,beta,qv,maf,cluster_i,gene_chr,gene_start,gene_end
0,SLC24A3,4.151806e-07,Esophagus_Mucosa,chr1_78663229_G_A_b38,-0.323393,0.000697,0.547222,7,chr20,19212646,19722937
2,CRISP3,9.577293e-07,Esophagus_Mucosa,chr1_78663229_G_A_b38,-0.314357,0.000697,0.547222,7,chr6,49727384,49744437
5,UPK3B,1.128828e-06,Esophagus_Mucosa,chr1_78663229_G_A_b38,-0.312264,0.000697,0.547222,7,chr7,76510428,76516521
6,CAMK2N1,1.279904e-06,Esophagus_Mucosa,chr1_78663229_G_A_b38,-0.311924,0.000697,0.547222,7,chr1,20482391,20486220
7,CALB2,1.424056e-06,Esophagus_Mucosa,chr1_78663229_G_A_b38,-0.309081,0.000697,0.547222,7,chr16,71358713,71390438

,Gene_set,Term,P-value,Adjusted P-value,Old P-value,Old adjusted P-value,Odds Ratio,Combined Score,Genes
0,MSigDB_Hallmark_2020,IL-2/STAT5 Signaling,0.007593,0.258158,0,0,2.699778,13.176380,ECM1;MAFF;ST3GAL4;PIM1;SH3BGRL2;EMP1;SNX9;MXD1...
1,MSigDB_Hallmark_2020,Adipogenesis,0.028074,0.477264,0,0,2.839948,10.146847,RIOK3;CCNG2;CIDEA;SNCG;TOB1;MGLL
2,MSigDB_Hallmark_2020,Wnt-beta Catenin Signaling,0.089269,0.991583,0,0,4.678030,11.302609,DKK4;DKK1
3,MSigDB_Hallmark_2020,Fatty Acid Metabolism,0.126703,0.991583,0,0,2.208283,4.562118,HPGD;TP53INP2;CIDEA;MGLL
4,MSigDB_Hallmark_2020,heme Metabolism,0.264516,0.991583,0,0,1.751745,2.329566,RIOK3;FBXO34;LPIN2

Skin_Sun_Exposed_Lower_leg
For Skin_Sun_Exposed_Lower_leg top 50 correction type = Bonferroni
Doing for top 50 gene

,gene_name,p_value,tissue,snp_id,beta,qv,maf,cluster_i,gene_chr,gene_start,gene_end
0,RP11-326C3.7,0.000201,Skin_Sun_Exposed_Lower_leg,chr5_174255970_A_G_b38,0.300963,0.451498,0.837278,2,chr11,310139,311141
1,RP11-574K11.24,0.000278,Skin_Sun_Exposed_Lower_leg,chr5_174255970_A_G_b38,0.297194,0.451498,0.837278,2,chr10,73742995,73744230
2,USP53,0.000462,Skin_Sun_Exposed_Lower_leg,chr5_174255970_A_G_b38,0.279352,0.451498,0.837278,2,chr4,119212645,119295517
3,AC112715.2,0.000662,Skin_Sun_Exposed_Lower_leg,chr5_174255970_A_G_b38,0.271122,0.517650,0.837278,2,chr2,237257091,237257676
4,RP11-585P4.5,0.001364,Skin_Sun_Exposed_Lower_leg,chr5_174255970_A_G_b38,0.263722,0.810098,0.837278,2,chr12,75483454,75489820

,Gene_set,Term,P-value,Adjusted P-value,Old P-value,Old adjusted P-value,Odds Ratio,Combined Score,Genes
0,MSigDB_Hallmark_2020,Apoptosis,0.008565,0.205555,0,0,5.505797,26.208116,TGFBR3;BNIP3L;TXNIP;AVPR1A
1,MSigDB_Hallmark_2020,Hypoxia,0.032161,0.385929,0,0,3.600573,12.375201,ERO1A;BNIP3L;MIF;PDK1
2,MSigDB_Hallmark_2020,Protein Secretion,0.132197,0.671190,0,0,7.855102,15.894489,ABCA1
3,MSigDB_Hallmark_2020,PI3K/AKT/mTOR Signaling,0.143329,0.671190,0,0,7.139147,13.868618,PDK1
4,MSigDB_Hallmark_2020,Glycolysis,0.164607,0.671190,0,0,2.881818,5.199354,ERO1A;MIF

Doing for top 50 gene

,gene_name,p_value,tissue,snp_id,beta,qv,maf,cluster_i,gene_chr,gene_start,gene_end
15,HIST1H1D,0.004015,Skin_Sun_Exposed_Lower_leg,chr5_174255970_A_G_b38,-0.230477,0.810098,0.837278,2,chr6,26234268,26234933
31,MMP28,0.007030,Skin_Sun_Exposed_Lower_leg,chr5_174255970_A_G_b38,-0.213391,0.810098,0.837278,2,chr17,35756249,35795707
34,CFAP157,0.008356,Skin_Sun_Exposed_Lower_leg,chr5_174255970_A_G_b38,-0.216319,0.822372,0.837278,2,chr9,127706992,127715337
35,HIST1H1E,0.008559,Skin_Sun_Exposed_Lower_leg,chr5_174255970_A_G_b38,-0.214718,0.822372,0.837278,2,chr6,26156354,26157107
38,C14orf80,0.009800,Skin_Sun_Exposed_Lower_leg,chr5_174255970_A_G_b38,-0.210532,0.822372,0.837278,2,chr14,105489855,105499575

,Gene_set,Term,P-value,Adjusted P-value,Old P-value,Old adjusted P-value,Odds Ratio,Combined Score,Genes
0,MSigDB_Hallmark_2020,Myogenesis,0.435758,0.710043,0,0,1.381268,1.147377,PKIA;MYOM2
1,MSigDB_Hallmark_2020,Interferon Alpha Response,0.448789,0.710043,0,0,1.729705,1.385844,IFI35
2,MSigDB_Hallmark_2020,UV Response Up,0.476788,0.710043,0,0,1.586839,1.175344,STIP1
3,MSigDB_Hallmark_2020,Glycolysis,0.522471,0.710043,0,0,1.385933,0.899728,TSTA3
4,MSigDB_Hallmark_2020,Epithelial Mesenchymal Transition,0.570794,0.710043,0,0,1.059646,0.594173,COL5A3;APLP1

Skin_Sun_Exposed_Lower_leg
For Skin_Sun_Exposed_Lower_leg top 100 correction type = Bonferroni
Doing for top 100 gene

,gene_name,p_value,tissue,snp_id,beta,qv,maf,cluster_i,gene_chr,gene_start,gene_end
0,RP11-326C3.7,0.000201,Skin_Sun_Exposed_Lower_leg,chr5_174255970_A_G_b38,0.300963,0.451498,0.837278,2,chr11,310139,311141
1,RP11-574K11.24,0.000278,Skin_Sun_Exposed_Lower_leg,chr5_174255970_A_G_b38,0.297194,0.451498,0.837278,2,chr10,73742995,73744230
2,USP53,0.000462,Skin_Sun_Exposed_Lower_leg,chr5_174255970_A_G_b38,0.279352,0.451498,0.837278,2,chr4,119212645,119295517
3,AC112715.2,0.000662,Skin_Sun_Exposed_Lower_leg,chr5_174255970_A_G_b38,0.271122,0.517650,0.837278,2,chr2,237257091,237257676
4,RP11-585P4.5,0.001364,Skin_Sun_Exposed_Lower_leg,chr5_174255970_A_G_b38,0.263722,0.810098,0.837278,2,chr12,75483454,75489820

,Gene_set,Term,P-value,Adjusted P-value,Old P-value,Old adjusted P-value,Odds Ratio,Combined Score,Genes
0,MSigDB_Hallmark_2020,Hypoxia,0.032164,0.842115,0,0,2.697354,9.270577,ERO1A;BNIP3L;MIF;PPFIA4;PFKP;PDK1
1,MSigDB_Hallmark_2020,Glycolysis,0.055047,0.842115,0,0,2.984707,8.654373,ERO1A;MIF;PPFIA4;PFKP
2,MSigDB_Hallmark_2020,Apoptosis,0.077608,0.842115,0,0,2.631579,6.726533,TGFBR3;BNIP3L;TXNIP;AVPR1A
3,MSigDB_Hallmark_2020,Inflammatory Response,0.219281,0.842115,0,0,1.720763,2.611089,ABCA1;OSMR;SLC7A2;TLR2
4,MSigDB_Hallmark_2020,Wnt-beta Catenin Signaling,0.246135,0.842115,0,0,3.877551,5.435842,DKK1

Doing for top 100 gene

,gene_name,p_value,tissue,snp_id,beta,qv,maf,cluster_i,gene_chr,gene_start,gene_end
15,HIST1H1D,0.004015,Skin_Sun_Exposed_Lower_leg,chr5_174255970_A_G_b38,-0.230477,0.810098,0.837278,2,chr6,26234268,26234933
31,MMP28,0.007030,Skin_Sun_Exposed_Lower_leg,chr5_174255970_A_G_b38,-0.213391,0.810098,0.837278,2,chr17,35756249,35795707
34,CFAP157,0.008356,Skin_Sun_Exposed_Lower_leg,chr5_174255970_A_G_b38,-0.216319,0.822372,0.837278,2,chr9,127706992,127715337
35,HIST1H1E,0.008559,Skin_Sun_Exposed_Lower_leg,chr5_174255970_A_G_b38,-0.214718,0.822372,0.837278,2,chr6,26156354,26157107
38,C14orf80,0.009800,Skin_Sun_Exposed_Lower_leg,chr5_174255970_A_G_b38,-0.210532,0.822372,0.837278,2,chr14,105489855,105499575

,Gene_set,Term,P-value,Adjusted P-value,Old P-value,Old adjusted P-value,Odds Ratio,Combined Score,Genes
0,MSigDB_Hallmark_2020,E2F Targets,0.002456,0.066320,0,0,8.311404,49.944039,CDC20;BIRC5;TK1;ASF1B
1,MSigDB_Hallmark_2020,KRAS Signaling Dn,0.006820,0.092066,0,0,3.921870,19.562046,GAMT;LFNG;RYR1;AKR1B10;CLPS;WNT16
2,MSigDB_Hallmark_2020,UV Response Up,0.037821,0.225416,0,0,3.408514,11.162471,DNAJA1;STIP1;FMO1;FKBP4
3,MSigDB_Hallmark_2020,G2-M Checkpoint,0.040021,0.225416,0,0,4.332188,13.942461,CDC20;TROAP;BIRC5
4,MSigDB_Hallmark_2020,Xenobiotic Metabolism,0.041744,0.225416,0,0,2.811278,8.929200,CYP2J2;CBR1;REG1A;FMO1;APOE

Skin_Sun_Exposed_Lower_leg
For Skin_Sun_Exposed_Lower_leg top 150 correction type = Bonferroni
Doing for top 150 gene

,gene_name,p_value,tissue,snp_id,beta,qv,maf,cluster_i,gene_chr,gene_start,gene_end
0,RP11-326C3.7,0.000201,Skin_Sun_Exposed_Lower_leg,chr5_174255970_A_G_b38,0.300963,0.451498,0.837278,2,chr11,310139,311141
1,RP11-574K11.24,0.000278,Skin_Sun_Exposed_Lower_leg,chr5_174255970_A_G_b38,0.297194,0.451498,0.837278,2,chr10,73742995,73744230
2,USP53,0.000462,Skin_Sun_Exposed_Lower_leg,chr5_174255970_A_G_b38,0.279352,0.451498,0.837278,2,chr4,119212645,119295517
3,AC112715.2,0.000662,Skin_Sun_Exposed_Lower_leg,chr5_174255970_A_G_b38,0.271122,0.517650,0.837278,2,chr2,237257091,237257676
4,RP11-585P4.5,0.001364,Skin_Sun_Exposed_Lower_leg,chr5_174255970_A_G_b38,0.263722,0.810098,0.837278,2,chr12,75483454,75489820

,Gene_set,Term,P-value,Adjusted P-value,Old P-value,Old adjusted P-value,Odds Ratio,Combined Score,Genes
0,MSigDB_Hallmark_2020,Glycolysis,0.020267,0.516795,0,0,3.051419,11.896821,ERO1A;STC1;MIF;MERTK;PPFIA4;PFKP
1,MSigDB_Hallmark_2020,Hypoxia,0.027200,0.516795,0,0,2.395370,8.634224,ERO1A;BNIP3L;GBE1;STC1;MIF;PPFIA4;PFKP;PDK1
2,MSigDB_Hallmark_2020,UV Response Dn,0.148825,0.960079,0,0,2.046897,3.899309,TGFBR3;CELF2;LPAR1;FBLN5
3,MSigDB_Hallmark_2020,Inflammatory Response,0.152598,0.960079,0,0,1.730651,3.253539,ABCA1;GPR183;LPAR1;OSMR;SLC7A2;TLR2
4,MSigDB_Hallmark_2020,Apoptosis,0.226155,0.960079,0,0,1.701149,2.528819,TGFBR3;BNIP3L;TXNIP;AVPR1A

Doing for top 150 gene

,gene_name,p_value,tissue,snp_id,beta,qv,maf,cluster_i,gene_chr,gene_start,gene_end
15,HIST1H1D,0.004015,Skin_Sun_Exposed_Lower_leg,chr5_174255970_A_G_b38,-0.230477,0.810098,0.837278,2,chr6,26234268,26234933
31,MMP28,0.007030,Skin_Sun_Exposed_Lower_leg,chr5_174255970_A_G_b38,-0.213391,0.810098,0.837278,2,chr17,35756249,35795707
34,CFAP157,0.008356,Skin_Sun_Exposed_Lower_leg,chr5_174255970_A_G_b38,-0.216319,0.822372,0.837278,2,chr9,127706992,127715337
35,HIST1H1E,0.008559,Skin_Sun_Exposed_Lower_leg,chr5_174255970_A_G_b38,-0.214718,0.822372,0.837278,2,chr6,26156354,26157107
38,C14orf80,0.009800,Skin_Sun_Exposed_Lower_leg,chr5_174255970_A_G_b38,-0.210532,0.822372,0.837278,2,chr14,105489855,105499575

,Gene_set,Term,P-value,Adjusted P-value,Old P-value,Old adjusted P-value,Odds Ratio,Combined Score,Genes
0,MSigDB_Hallmark_2020,KRAS Signaling Dn,0.000194,0.006775,0,0,4.639098,39.663518,GAMT;LFNG;RYR1;AKR1B10;CLPS;CPB1;KRT1;GP2;WNT1...
1,MSigDB_Hallmark_2020,E2F Targets,0.001495,0.026168,0,0,7.166667,46.622237,CDC20;RRM2;BIRC5;TK1;ASF1B
2,MSigDB_Hallmark_2020,Xenobiotic Metabolism,0.023805,0.229730,0,0,2.657034,9.931626,CYP2J2;CBR1;NQO1;REG1A;FMO1;APOE;PSMB10
3,MSigDB_Hallmark_2020,G2-M Checkpoint,0.026255,0.229730,0,0,3.933614,14.317971,CDC20;UBE2C;TROAP;BIRC5
4,MSigDB_Hallmark_2020,UV Response Up,0.123546,0.864824,0,0,2.211435,4.624420,DNAJA1;STIP1;FMO1;FKBP4

Skin_Sun_Exposed_Lower_leg
For Skin_Sun_Exposed_Lower_leg top 200 correction type = Bonferroni
Doing for top 200 gene

,gene_name,p_value,tissue,snp_id,beta,qv,maf,cluster_i,gene_chr,gene_start,gene_end
0,RP11-326C3.7,0.000201,Skin_Sun_Exposed_Lower_leg,chr5_174255970_A_G_b38,0.300963,0.451498,0.837278,2,chr11,310139,311141
1,RP11-574K11.24,0.000278,Skin_Sun_Exposed_Lower_leg,chr5_174255970_A_G_b38,0.297194,0.451498,0.837278,2,chr10,73742995,73744230
2,USP53,0.000462,Skin_Sun_Exposed_Lower_leg,chr5_174255970_A_G_b38,0.279352,0.451498,0.837278,2,chr4,119212645,119295517
3,AC112715.2,0.000662,Skin_Sun_Exposed_Lower_leg,chr5_174255970_A_G_b38,0.271122,0.517650,0.837278,2,chr2,237257091,237257676
4,RP11-585P4.5,0.001364,Skin_Sun_Exposed_Lower_leg,chr5_174255970_A_G_b38,0.263722,0.810098,0.837278,2,chr12,75483454,75489820

,Gene_set,Term,P-value,Adjusted P-value,Old P-value,Old adjusted P-value,Odds Ratio,Combined Score,Genes
0,MSigDB_Hallmark_2020,Glycolysis,0.067727,0.772403,0,0,2.230418,6.004903,ERO1A;STC1;MIF;MERTK;PPFIA4;PFKP
1,MSigDB_Hallmark_2020,Wnt-beta Catenin Signaling,0.104837,0.772403,0,0,4.174845,9.415744,DLL1;DKK1
2,MSigDB_Hallmark_2020,Protein Secretion,0.104837,0.772403,0,0,4.174845,9.415744,ABCA1;BNIP3
3,MSigDB_Hallmark_2020,Hypoxia,0.108658,0.772403,0,0,1.744238,3.871427,ERO1A;BNIP3L;GBE1;STC1;MIF;PPFIA4;PFKP;PDK1
4,MSigDB_Hallmark_2020,Inflammatory Response,0.108658,0.772403,0,0,1.744238,3.871427,ABCA1;MARCO;GPR183;NAMPT;LPAR1;OSMR;SLC7A2;TLR2

Doing for top 200 gene

,gene_name,p_value,tissue,snp_id,beta,qv,maf,cluster_i,gene_chr,gene_start,gene_end
15,HIST1H1D,0.004015,Skin_Sun_Exposed_Lower_leg,chr5_174255970_A_G_b38,-0.230477,0.810098,0.837278,2,chr6,26234268,26234933
31,MMP28,0.007030,Skin_Sun_Exposed_Lower_leg,chr5_174255970_A_G_b38,-0.213391,0.810098,0.837278,2,chr17,35756249,35795707
34,CFAP157,0.008356,Skin_Sun_Exposed_Lower_leg,chr5_174255970_A_G_b38,-0.216319,0.822372,0.837278,2,chr9,127706992,127715337
35,HIST1H1E,0.008559,Skin_Sun_Exposed_Lower_leg,chr5_174255970_A_G_b38,-0.214718,0.822372,0.837278,2,chr6,26156354,26157107
38,C14orf80,0.009800,Skin_Sun_Exposed_Lower_leg,chr5_174255970_A_G_b38,-0.210532,0.822372,0.837278,2,chr14,105489855,105499575

,Gene_set,Term,P-value,Adjusted P-value,Old P-value,Old adjusted P-value,Odds Ratio,Combined Score,Genes
0,MSigDB_Hallmark_2020,KRAS Signaling Dn,0.000490,0.018636,0,0,3.796580,28.930832,GAMT;RYR1;LFNG;CLPS;AKR1B10;SERPINB2;CPB1;KRT1...
1,MSigDB_Hallmark_2020,Xenobiotic Metabolism,0.001304,0.024781,0,0,3.314732,22.016896,CYP2J2;CBR1;NQO1;CA2;CYP2S1;ID2;REG1A;FMO1;GST...
2,MSigDB_Hallmark_2020,E2F Targets,0.005270,0.066753,0,0,5.257835,27.581183,CDC20;RRM2;BIRC5;TK1;ASF1B
3,MSigDB_Hallmark_2020,Estrogen Response Late,0.007646,0.072634,0,0,2.696812,13.143205,CDC20;SCUBE2;TSTA3;CLIC3;CISH;CA2;ID2;ANXA9;FK...
4,MSigDB_Hallmark_2020,G2-M Checkpoint,0.016696,0.126890,0,0,3.778462,15.463681,CDC20;CDC45;UBE2C;TROAP;BIRC5

Adipose_Subcutaneous
For Adipose_Subcutaneous top 50 correction type = Bonferroni
Doing for top 50 gene

,gene_name,p_value,tissue,snp_id,beta,qv,maf,cluster_i,gene_chr,gene_start,gene_end
0,SPX,0.000090,Adipose_Subcutaneous,chr10_17384475_A_C_b38,0.283536,0.276953,0.769494,1,chr12,21526307,21537377
8,MYZAP,0.000984,Adipose_Subcutaneous,chr10_17384475_A_C_b38,0.231936,0.357333,0.769494,1,chr15,57591941,57685364
12,LINC01485,0.001189,Adipose_Subcutaneous,chr10_17384475_A_C_b38,0.230094,0.363130,0.769494,1,chr5,173786790,173809039
19,MUC7,0.002312,Adipose_Subcutaneous,chr10_17384475_A_C_b38,0.186557,0.448736,0.769494,1,chr4,70430492,70482997
25,HSPB7,0.003147,Adipose_Subcutaneous,chr10_17384475_A_C_b38,0.210125,0.480630,0.769494,1,chr1,16014028,16019594

,Gene_set,Term,P-value,Adjusted P-value,Old P-value,Old adjusted P-value,Odds Ratio,Combined Score,Genes
0,MSigDB_Hallmark_2020,Adipogenesis,0.000002,0.000042,0,0,12.034348,160.085520,SLC25A1;GPAM;RETSAT;FZD4;LEP;ME1;ELOVL6;DHCR7
1,MSigDB_Hallmark_2020,mTORC1 Signaling,0.000500,0.006249,0,0,6.888158,52.357418,ELOVL5;SCD;ME1;ELOVL6;VLDLR;DHCR7
2,MSigDB_Hallmark_2020,Fatty Acid Metabolism,0.003882,0.032349,0,0,7.005435,38.890188,RETSAT;ELOVL5;FASN;ME1
3,MSigDB_Hallmark_2020,Estrogen Response Early,0.005351,0.033445,0,0,4.947028,25.875040,CALB2;ELOVL5;KRT15;FASN;DHCR7
4,MSigDB_Hallmark_2020,Cholesterol Homeostasis,0.014369,0.059870,0,0,6.512318,27.629824,SCD;FASN;DHCR7

Doing for top 50 gene

,gene_name,p_value,tissue,snp_id,beta,qv,maf,cluster_i,gene_chr,gene_start,gene_end
1,C4B,0.000139,Adipose_Subcutaneous,chr10_17384475_A_C_b38,-0.270787,0.276953,0.769494,1,chr6,32014762,32035418
2,TPGS1,0.000430,Adipose_Subcutaneous,chr10_17384475_A_C_b38,-0.255081,0.332200,0.769494,1,chr19,507834,519654
3,HLX,0.000486,Adipose_Subcutaneous,chr10_17384475_A_C_b38,-0.250685,0.332200,0.769494,1,chr1,220879400,220885059
4,JUND,0.000568,Adipose_Subcutaneous,chr10_17384475_A_C_b38,-0.241491,0.332200,0.769494,1,chr19,18279760,18281622
5,JUN,0.000581,Adipose_Subcutaneous,chr10_17384475_A_C_b38,-0.234458,0.332200,0.769494,1,chr1,58780788,58784327

,Gene_set,Term,P-value,Adjusted P-value,Old P-value,Old adjusted P-value,Odds Ratio,Combined Score,Genes
0,MSigDB_Hallmark_2020,TNF-alpha Signaling via NF-kB,1.723534e-12,5.687661e-11,0,0,15.411765,417.452992,PPP1R15A;DUSP5;JUN;CEBPD;GADD45A;DUSP1;FOS;CXC...
1,MSigDB_Hallmark_2020,p53 Pathway,4.397842e-05,7.256439e-04,0,0,8.813626,88.416634,PPP1R15A;JUN;GADD45A;FOS;MXD1;ATF3;HBEGF
2,MSigDB_Hallmark_2020,Inflammatory Response,1.843711e-03,1.757424e-02,0,0,5.256198,33.092894,CCRL2;IRF7;MXD1;SELE;CX3CL1;HBEGF
3,MSigDB_Hallmark_2020,Hypoxia,2.130210e-03,1.757424e-02,0,0,5.097594,31.358023,PPP1R15A;JUN;ZFP36;DUSP1;FOS;ATF3
4,MSigDB_Hallmark_2020,TGF-beta Signaling,2.324497e-02,1.534168e-01,0,0,9.553922,35.938668,PPP1R15A;JUNB

Adipose_Subcutaneous
For Adipose_Subcutaneous top 100 correction type = Bonferroni
Doing for top 100 gene

,gene_name,p_value,tissue,snp_id,beta,qv,maf,cluster_i,gene_chr,gene_start,gene_end
0,SPX,0.000090,Adipose_Subcutaneous,chr10_17384475_A_C_b38,0.283536,0.276953,0.769494,1,chr12,21526307,21537377
8,MYZAP,0.000984,Adipose_Subcutaneous,chr10_17384475_A_C_b38,0.231936,0.357333,0.769494,1,chr15,57591941,57685364
12,LINC01485,0.001189,Adipose_Subcutaneous,chr10_17384475_A_C_b38,0.230094,0.363130,0.769494,1,chr5,173786790,173809039
19,MUC7,0.002312,Adipose_Subcutaneous,chr10_17384475_A_C_b38,0.186557,0.448736,0.769494,1,chr4,70430492,70482997
25,HSPB7,0.003147,Adipose_Subcutaneous,chr10_17384475_A_C_b38,0.210125,0.480630,0.769494,1,chr1,16014028,16019594

,Gene_set,Term,P-value,Adjusted P-value,Old P-value,Old adjusted P-value,Odds Ratio,Combined Score,Genes
0,MSigDB_Hallmark_2020,Fatty Acid Metabolism,0.000037,0.001227,0,0,7.551383,77.022766,NSDHL;RETSAT;ELOVL5;ACSL1;FASN;GPD1;ME1;DHCR24
1,MSigDB_Hallmark_2020,Adipogenesis,0.000290,0.004785,0,0,5.422666,44.170932,SLC25A1;GPAM;RETSAT;FZD4;LEP;ME1;ELOVL6;DHCR7
2,MSigDB_Hallmark_2020,Cholesterol Homeostasis,0.000487,0.005355,0,0,6.984802,53.277026,NSDHL;ACSS2;SCD;FASN;ALDOC;DHCR7
3,MSigDB_Hallmark_2020,mTORC1 Signaling,0.000944,0.007785,0,0,4.454759,31.030842,ELOVL5;SCD;ME1;ELOVL6;DHCR24;VLDLR;DHCR7;ACACA
4,MSigDB_Hallmark_2020,Pperoxisome,0.006308,0.041631,0,0,6.152244,31.167206,RETSAT;ELOVL5;ACSL1;DHCR24

Doing for top 100 gene

,gene_name,p_value,tissue,snp_id,beta,qv,maf,cluster_i,gene_chr,gene_start,gene_end
1,C4B,0.000139,Adipose_Subcutaneous,chr10_17384475_A_C_b38,-0.270787,0.276953,0.769494,1,chr6,32014762,32035418
2,TPGS1,0.000430,Adipose_Subcutaneous,chr10_17384475_A_C_b38,-0.255081,0.332200,0.769494,1,chr19,507834,519654
3,HLX,0.000486,Adipose_Subcutaneous,chr10_17384475_A_C_b38,-0.250685,0.332200,0.769494,1,chr1,220879400,220885059
4,JUND,0.000568,Adipose_Subcutaneous,chr10_17384475_A_C_b38,-0.241491,0.332200,0.769494,1,chr19,18279760,18281622
5,JUN,0.000581,Adipose_Subcutaneous,chr10_17384475_A_C_b38,-0.234458,0.332200,0.769494,1,chr1,58780788,58784327

,Gene_set,Term,P-value,Adjusted P-value,Old P-value,Old adjusted P-value,Odds Ratio,Combined Score,Genes
0,MSigDB_Hallmark_2020,TNF-alpha Signaling via NF-kB,4.443797e-14,1.733081e-12,0,0,10.292863,316.450803,PPP1R15A;DUSP5;JUN;CEBPD;GADD45A;DUSP1;TNFAIP3...
1,MSigDB_Hallmark_2020,p53 Pathway,6.745234e-04,1.315321e-02,0,0,4.714286,34.421377,PPP1R15A;JUN;GADD45A;FOS;MXD1;ATF3;HBEGF;ZFP36L1
2,MSigDB_Hallmark_2020,Hypoxia,1.420051e-03,1.846067e-02,0,0,3.762238,24.669227,PPP1R15A;ERO1A;JUN;ZFP36;CDKN1B;DUSP1;TNFAIP3;...
3,MSigDB_Hallmark_2020,Inflammatory Response,4.583627e-03,3.670387e-02,0,0,3.377857,18.190657,CXCL8;CCRL2;IRF7;OLR1;MXD1;SELE;CX3CL1;HBEGF
4,MSigDB_Hallmark_2020,Apoptosis,4.705624e-03,3.670387e-02,0,0,4.264278,22.852251,JUN;WEE1;CDKN1B;GADD45A;MMP2;ATF3

Adipose_Subcutaneous
For Adipose_Subcutaneous top 150 correction type = Bonferroni
Doing for top 150 gene

,gene_name,p_value,tissue,snp_id,beta,qv,maf,cluster_i,gene_chr,gene_start,gene_end
0,SPX,0.000090,Adipose_Subcutaneous,chr10_17384475_A_C_b38,0.283536,0.276953,0.769494,1,chr12,21526307,21537377
8,MYZAP,0.000984,Adipose_Subcutaneous,chr10_17384475_A_C_b38,0.231936,0.357333,0.769494,1,chr15,57591941,57685364
12,LINC01485,0.001189,Adipose_Subcutaneous,chr10_17384475_A_C_b38,0.230094,0.363130,0.769494,1,chr5,173786790,173809039
19,MUC7,0.002312,Adipose_Subcutaneous,chr10_17384475_A_C_b38,0.186557,0.448736,0.769494,1,chr4,70430492,70482997
25,HSPB7,0.003147,Adipose_Subcutaneous,chr10_17384475_A_C_b38,0.210125,0.480630,0.769494,1,chr1,16014028,16019594

,Gene_set,Term,P-value,Adjusted P-value,Old P-value,Old adjusted P-value,Odds Ratio,Combined Score,Genes
0,MSigDB_Hallmark_2020,Fatty Acid Metabolism,0.000018,0.000664,0,0,6.416667,70.126556,NSDHL;RETSAT;MDH1;ELOVL5;ACSL1;FASN;GPD1;ME1;D...
1,MSigDB_Hallmark_2020,Adipogenesis,0.000043,0.000800,0,0,5.126147,51.513118,SLC25A1;LIPE;GPAM;RETSAT;FZD4;LEP;GBE1;ME1;ELO...
2,MSigDB_Hallmark_2020,Pperoxisome,0.000742,0.008454,0,0,6.581597,47.432414,ABCD2;RETSAT;ACSL1;ELOVL5;ALB;DHCR24
3,MSigDB_Hallmark_2020,mTORC1 Signaling,0.000914,0.008454,0,0,3.713294,25.984612,ELOVL5;SCD;GBE1;ME1;ELOVL6;DHCR24;VLDLR;DHCR7;...
4,MSigDB_Hallmark_2020,Cholesterol Homeostasis,0.003985,0.029485,0,0,4.500000,24.864035,NSDHL;ACSS2;SCD;FASN;ALDOC;DHCR7

Doing for top 150 gene

,gene_name,p_value,tissue,snp_id,beta,qv,maf,cluster_i,gene_chr,gene_start,gene_end
1,C4B,0.000139,Adipose_Subcutaneous,chr10_17384475_A_C_b38,-0.270787,0.276953,0.769494,1,chr6,32014762,32035418
2,TPGS1,0.000430,Adipose_Subcutaneous,chr10_17384475_A_C_b38,-0.255081,0.332200,0.769494,1,chr19,507834,519654
3,HLX,0.000486,Adipose_Subcutaneous,chr10_17384475_A_C_b38,-0.250685,0.332200,0.769494,1,chr1,220879400,220885059
4,JUND,0.000568,Adipose_Subcutaneous,chr10_17384475_A_C_b38,-0.241491,0.332200,0.769494,1,chr19,18279760,18281622
5,JUN,0.000581,Adipose_Subcutaneous,chr10_17384475_A_C_b38,-0.234458,0.332200,0.769494,1,chr1,58780788,58784327

,Gene_set,Term,P-value,Adjusted P-value,Old P-value,Old adjusted P-value,Odds Ratio,Combined Score,Genes
0,MSigDB_Hallmark_2020,TNF-alpha Signaling via NF-kB,1.931866e-15,7.727464e-14,0,0,8.637407,292.637845,PPP1R15A;PTGER4;CEBPD;TNFAIP3;SLC2A3;CXCL3;ETS...
1,MSigDB_Hallmark_2020,Hypoxia,4.326648e-05,8.653295e-04,0,0,4.074937,40.945511,PPP1R15A;ERO1A;JUN;CDKN1B;TES;DUSP1;TNFAIP3;ST...
2,MSigDB_Hallmark_2020,p53 Pathway,2.440482e-03,3.253976e-02,0,0,3.465310,20.845778,PPP1R15A;JUN;GADD45A;FOS;MXD1;KLF4;ATF3;HBEGF;...
3,MSigDB_Hallmark_2020,Interferon Alpha Response,3.508818e-03,3.508818e-02,0,0,4.633578,26.191192,CD74;IFI27;CCRL2;MX1;IRF7;ISG15
4,MSigDB_Hallmark_2020,Inflammatory Response,5.853758e-03,4.683006e-02,0,0,2.796992,14.378419,PTGER4;CXCL8;RGS1;CCRL2;IRF7;OLR1;MXD1;SELE;CX...

Adipose_Subcutaneous
For Adipose_Subcutaneous top 200 correction type = Bonferroni
Doing for top 200 gene

,gene_name,p_value,tissue,snp_id,beta,qv,maf,cluster_i,gene_chr,gene_start,gene_end
0,SPX,0.000090,Adipose_Subcutaneous,chr10_17384475_A_C_b38,0.283536,0.276953,0.769494,1,chr12,21526307,21537377
8,MYZAP,0.000984,Adipose_Subcutaneous,chr10_17384475_A_C_b38,0.231936,0.357333,0.769494,1,chr15,57591941,57685364
12,LINC01485,0.001189,Adipose_Subcutaneous,chr10_17384475_A_C_b38,0.230094,0.363130,0.769494,1,chr5,173786790,173809039
19,MUC7,0.002312,Adipose_Subcutaneous,chr10_17384475_A_C_b38,0.186557,0.448736,0.769494,1,chr4,70430492,70482997
25,HSPB7,0.003147,Adipose_Subcutaneous,chr10_17384475_A_C_b38,0.210125,0.480630,0.769494,1,chr1,16014028,16019594

,Gene_set,Term,P-value,Adjusted P-value,Old P-value,Old adjusted P-value,Odds Ratio,Combined Score,Genes
0,MSigDB_Hallmark_2020,Adipogenesis,0.000006,0.000220,0,0,5.077224,61.230637,SLC25A1;RETSAT;FZD4;GBE1;ADIPOQ;ELOVL6;FAH;ADI...
1,MSigDB_Hallmark_2020,Fatty Acid Metabolism,0.000210,0.003983,0,0,4.665414,39.517331,NSDHL;RETSAT;MDH1;ACSL1;ELOVL5;FASN;GPD1;ME1;D...
2,MSigDB_Hallmark_2020,Oxidative Phosphorylation,0.002258,0.028602,0,0,9.584184,58.398789,MAOB;RETSAT;MDH1;DLAT
3,MSigDB_Hallmark_2020,Pperoxisome,0.003280,0.031157,0,0,4.820876,27.575395,ABCD2;RETSAT;ACSL1;ELOVL5;ALB;DHCR24
4,MSigDB_Hallmark_2020,mTORC1 Signaling,0.007566,0.057501,0,0,2.699561,13.184922,ELOVL5;SCD;GBE1;ME1;ELOVL6;DHCR24;VLDLR;DHCR7;...

Doing for top 200 gene

,gene_name,p_value,tissue,snp_id,beta,qv,maf,cluster_i,gene_chr,gene_start,gene_end
1,C4B,0.000139,Adipose_Subcutaneous,chr10_17384475_A_C_b38,-0.270787,0.276953,0.769494,1,chr6,32014762,32035418
2,TPGS1,0.000430,Adipose_Subcutaneous,chr10_17384475_A_C_b38,-0.255081,0.332200,0.769494,1,chr19,507834,519654
3,HLX,0.000486,Adipose_Subcutaneous,chr10_17384475_A_C_b38,-0.250685,0.332200,0.769494,1,chr1,220879400,220885059
4,JUND,0.000568,Adipose_Subcutaneous,chr10_17384475_A_C_b38,-0.241491,0.332200,0.769494,1,chr19,18279760,18281622
5,JUN,0.000581,Adipose_Subcutaneous,chr10_17384475_A_C_b38,-0.234458,0.332200,0.769494,1,chr1,58780788,58784327

,Gene_set,Term,P-value,Adjusted P-value,Old P-value,Old adjusted P-value,Odds Ratio,Combined Score,Genes
0,MSigDB_Hallmark_2020,TNF-alpha Signaling via NF-kB,3.683206e-17,1.510114e-15,0,0,8.021243,303.525157,PTGER4;PPP1R15A;CDKN1A;CEBPD;TNFAIP3;SLC2A3;PT...
1,MSigDB_Hallmark_2020,Interferon Gamma Response,1.158668e-04,2.375270e-03,0,0,3.510334,31.814398,CD74;CDKN1A;IL4R;VCAM1;MX2;MX1;TNFAIP3;ISG15;P...
2,MSigDB_Hallmark_2020,Hypoxia,2.796254e-04,3.821548e-03,0,0,3.201395,26.194004,ERO1A;PPP1R15A;JUN;CDKN1A;TES;CDKN1B;DUSP1;STC...
3,MSigDB_Hallmark_2020,Interferon Alpha Response,6.930590e-04,7.103855e-03,0,0,4.860677,35.358487,IFIH1;CD74;IL4R;IFI27;CCRL2;MX1;IRF7;ISG15
4,MSigDB_Hallmark_2020,Inflammatory Response,2.117655e-03,1.736477e-02,0,0,2.775459,17.089740,PTGER4;CDKN1A;IL4R;CXCL8;SELE;CX3CL1;ICAM1;RGS...

Spleen
For Spleen top 50 correction type = Bonferroni
Doing for top 50 gene

,gene_name,p_value,tissue,snp_id,beta,qv,maf,cluster_i,gene_chr,gene_start,gene_end
0,RP11-678G14.3,0.000345,Spleen,chr10_80647340_G_GGT_b38,0.429374,0.999514,0.800377,4,chr19,21570822,21587322
1,BTNL8,0.000567,Spleen,chr10_80647340_G_GGT_b38,0.406682,0.999514,0.800377,4,chr5,180899077,180950906
2,KCNH3,0.001423,Spleen,chr10_80647340_G_GGT_b38,0.370250,0.999514,0.800377,4,chr12,49539157,49558294
3,CLEC7A,0.001670,Spleen,chr10_80647340_G_GGT_b38,0.370797,0.999514,0.800377,4,chr12,10116777,10130258
6,HAL,0.005032,Spleen,chr10_80647340_G_GGT_b38,0.337432,0.999514,0.800377,4,chr12,95972662,95996365

,Gene_set,Term,P-value,Adjusted P-value,Old P-value,Old adjusted P-value,Odds Ratio,Combined Score,Genes
0,MSigDB_Hallmark_2020,Androgen Response,0.212772,0.71475,0,0,4.442857,6.875480,KRT19
1,MSigDB_Hallmark_2020,Myogenesis,0.220088,0.71475,0,0,2.356360,3.566884,ITGA7;MYOM2
2,MSigDB_Hallmark_2020,Adipogenesis,0.344452,0.71475,0,0,2.459184,2.620997,ITGA7
3,MSigDB_Hallmark_2020,IL-6/JAK/STAT3 Signaling,0.388047,0.71475,0,0,2.104956,1.992611,TLR2
4,MSigDB_Hallmark_2020,KRAS Signaling Dn,0.415518,0.71475,0,0,1.920142,1.686323,UPK3B

Doing for top 50 gene

,gene_name,p_value,tissue,snp_id,beta,qv,maf,cluster_i,gene_chr,gene_start,gene_end
4,SNHG5,0.002405,Spleen,chr10_80647340_G_GGT_b38,-0.353937,0.999514,0.800377,4,chr6,85660950,85678736
5,RP11-322E11.5,0.003401,Spleen,chr10_80647340_G_GGT_b38,-0.354299,0.999514,0.800377,4,chr18,35443869,35467088
9,SNHG9,0.006665,Spleen,chr10_80647340_G_GGT_b38,-0.318886,0.999514,0.800377,4,chr16,1964959,1965509
11,HAMP,0.007883,Spleen,chr10_80647340_G_GGT_b38,-0.319683,0.999514,0.800377,4,chr19,35280716,35285143
12,AC016739.2,0.008736,Spleen,chr10_80647340_G_GGT_b38,-0.318259,0.999514,0.800377,4,chr2,176200908,176201252

,Gene_set,Term,P-value,Adjusted P-value,Old P-value,Old adjusted P-value,Odds Ratio,Combined Score,Genes
0,MSigDB_Hallmark_2020,Myc Targets V2,0.003182,0.028636,0,0,30.480836,175.274680,NOP2;HSPE1
1,MSigDB_Hallmark_2020,Myc Targets V1,0.144905,0.514583,0,0,6.930159,13.386836,HSPE1
2,MSigDB_Hallmark_2020,Complement,0.171528,0.514583,0,0,2.800650,4.937578,ANG;HSPA1A
3,MSigDB_Hallmark_2020,Glycolysis,0.388047,0.600675,0,0,2.104956,1.992611,ANG
4,MSigDB_Hallmark_2020,mTORC1 Signaling,0.400021,0.600675,0,0,2.021475,1.852151,HSPE1

Spleen
For Spleen top 100 correction type = Bonferroni
Doing for top 100 gene

,gene_name,p_value,tissue,snp_id,beta,qv,maf,cluster_i,gene_chr,gene_start,gene_end
0,RP11-678G14.3,0.000345,Spleen,chr10_80647340_G_GGT_b38,0.429374,0.999514,0.800377,4,chr19,21570822,21587322
1,BTNL8,0.000567,Spleen,chr10_80647340_G_GGT_b38,0.406682,0.999514,0.800377,4,chr5,180899077,180950906
2,KCNH3,0.001423,Spleen,chr10_80647340_G_GGT_b38,0.370250,0.999514,0.800377,4,chr12,49539157,49558294
3,CLEC7A,0.001670,Spleen,chr10_80647340_G_GGT_b38,0.370797,0.999514,0.800377,4,chr12,10116777,10130258
6,HAL,0.005032,Spleen,chr10_80647340_G_GGT_b38,0.337432,0.999514,0.800377,4,chr12,95972662,95996365

,Gene_set,Term,P-value,Adjusted P-value,Old P-value,Old adjusted P-value,Odds Ratio,Combined Score,Genes
0,MSigDB_Hallmark_2020,Allograft Rejection,0.075696,0.79057,0,0,2.647388,6.833005,KRT1;CFP;ELANE;TLR2
1,MSigDB_Hallmark_2020,KRAS Signaling Dn,0.287501,0.79057,0,0,1.940590,2.419000,KRT1;UPK3B
2,MSigDB_Hallmark_2020,Androgen Response,0.381978,0.79057,0,0,2.173737,2.091989,KRT19
3,MSigDB_Hallmark_2020,Estrogen Response Early,0.419099,0.79057,0,0,1.426230,1.240319,KRT19;MYB
4,MSigDB_Hallmark_2020,Apical Junction,0.426964,0.79057,0,0,1.402897,1.193942,COL17A1;CLDN9

Doing for top 100 gene

,gene_name,p_value,tissue,snp_id,beta,qv,maf,cluster_i,gene_chr,gene_start,gene_end
4,SNHG5,0.002405,Spleen,chr10_80647340_G_GGT_b38,-0.353937,0.999514,0.800377,4,chr6,85660950,85678736
5,RP11-322E11.5,0.003401,Spleen,chr10_80647340_G_GGT_b38,-0.354299,0.999514,0.800377,4,chr18,35443869,35467088
9,SNHG9,0.006665,Spleen,chr10_80647340_G_GGT_b38,-0.318886,0.999514,0.800377,4,chr16,1964959,1965509
11,HAMP,0.007883,Spleen,chr10_80647340_G_GGT_b38,-0.319683,0.999514,0.800377,4,chr19,35280716,35285143
12,AC016739.2,0.008736,Spleen,chr10_80647340_G_GGT_b38,-0.318259,0.999514,0.800377,4,chr2,176200908,176201252

,Gene_set,Term,P-value,Adjusted P-value,Old P-value,Old adjusted P-value,Odds Ratio,Combined Score,Genes
0,MSigDB_Hallmark_2020,Myc Targets V2,0.014297,0.285938,0,0,13.576138,57.667550,NOP2;HSPE1
1,MSigDB_Hallmark_2020,Hypoxia,0.080567,0.475791,0,0,2.585484,6.511985,EFNA1;CSRP2;HSPA5;ACKR3
2,MSigDB_Hallmark_2020,Glycolysis,0.086908,0.475791,0,0,3.038298,7.422260,HSPA5;ANG;FKBP4
3,MSigDB_Hallmark_2020,mTORC1 Signaling,0.095158,0.475791,0,0,2.912925,6.851824,HSPA5;CACYBP;HSPE1
4,MSigDB_Hallmark_2020,Complement,0.219472,0.658623,0,0,1.917568,2.908047,HSPA5;ANG;HSPA1A

Spleen
For Spleen top 150 correction type = Bonferroni
Doing for top 150 gene

,gene_name,p_value,tissue,snp_id,beta,qv,maf,cluster_i,gene_chr,gene_start,gene_end
0,RP11-678G14.3,0.000345,Spleen,chr10_80647340_G_GGT_b38,0.429374,0.999514,0.800377,4,chr19,21570822,21587322
1,BTNL8,0.000567,Spleen,chr10_80647340_G_GGT_b38,0.406682,0.999514,0.800377,4,chr5,180899077,180950906
2,KCNH3,0.001423,Spleen,chr10_80647340_G_GGT_b38,0.370250,0.999514,0.800377,4,chr12,49539157,49558294
3,CLEC7A,0.001670,Spleen,chr10_80647340_G_GGT_b38,0.370797,0.999514,0.800377,4,chr12,10116777,10130258
6,HAL,0.005032,Spleen,chr10_80647340_G_GGT_b38,0.337432,0.999514,0.800377,4,chr12,95972662,95996365

,Gene_set,Term,P-value,Adjusted P-value,Old P-value,Old adjusted P-value,Odds Ratio,Combined Score,Genes
0,MSigDB_Hallmark_2020,Allograft Rejection,0.032205,0.901752,0,0,2.698077,9.269569,KRT1;PRF1;CFP;ELANE;TLR2;PF4
1,MSigDB_Hallmark_2020,KRAS Signaling Dn,0.073545,0.982041,0,0,2.695763,7.035555,TG;KRT1;UPK3B;MEFV
2,MSigDB_Hallmark_2020,Myogenesis,0.123758,0.982041,0,0,1.984412,4.146281,CFD;MYBPC3;STC2;ITGA7;MYOM2
3,MSigDB_Hallmark_2020,Reactive Oxygen Species Pathway,0.241320,0.982041,0,0,4.091083,5.816020,MPO
4,MSigDB_Hallmark_2020,Estrogen Response Early,0.360910,0.982041,0,0,1.433333,1.460748,KRT19;STC2;MYB

Doing for top 150 gene

,gene_name,p_value,tissue,snp_id,beta,qv,maf,cluster_i,gene_chr,gene_start,gene_end
4,SNHG5,0.002405,Spleen,chr10_80647340_G_GGT_b38,-0.353937,0.999514,0.800377,4,chr6,85660950,85678736
5,RP11-322E11.5,0.003401,Spleen,chr10_80647340_G_GGT_b38,-0.354299,0.999514,0.800377,4,chr18,35443869,35467088
9,SNHG9,0.006665,Spleen,chr10_80647340_G_GGT_b38,-0.318886,0.999514,0.800377,4,chr16,1964959,1965509
11,HAMP,0.007883,Spleen,chr10_80647340_G_GGT_b38,-0.319683,0.999514,0.800377,4,chr19,35280716,35285143
12,AC016739.2,0.008736,Spleen,chr10_80647340_G_GGT_b38,-0.318259,0.999514,0.800377,4,chr2,176200908,176201252

,Gene_set,Term,P-value,Adjusted P-value,Old P-value,Old adjusted P-value,Odds Ratio,Combined Score,Genes
0,MSigDB_Hallmark_2020,Myc Targets V2,0.002407,0.050890,0,0,15.267857,92.052670,NOP2;HSPE1;HSPD1
1,MSigDB_Hallmark_2020,Hypoxia,0.003393,0.050890,0,0,3.564868,20.270359,EFNA1;IL6;CSRP2;HSPA5;ACKR3;ALDOB;CP;IER3
2,MSigDB_Hallmark_2020,Myc Targets V1,0.013595,0.108288,0,0,7.035165,30.237386,HSPE1;NME1;HSPD1
3,MSigDB_Hallmark_2020,Unfolded Protein Response,0.018899,0.108288,0,0,6.094286,24.186034,HSPA5;MTHFD2;HYOU1
4,MSigDB_Hallmark_2020,Glycolysis,0.021678,0.108288,0,0,3.410628,13.067658,HSPA5;ANG;ALDOB;FKBP4;IER3

Spleen
For Spleen top 200 correction type = Bonferroni
Doing for top 200 gene

,gene_name,p_value,tissue,snp_id,beta,qv,maf,cluster_i,gene_chr,gene_start,gene_end
0,RP11-678G14.3,0.000345,Spleen,chr10_80647340_G_GGT_b38,0.429374,0.999514,0.800377,4,chr19,21570822,21587322
1,BTNL8,0.000567,Spleen,chr10_80647340_G_GGT_b38,0.406682,0.999514,0.800377,4,chr5,180899077,180950906
2,KCNH3,0.001423,Spleen,chr10_80647340_G_GGT_b38,0.370250,0.999514,0.800377,4,chr12,49539157,49558294
3,CLEC7A,0.001670,Spleen,chr10_80647340_G_GGT_b38,0.370797,0.999514,0.800377,4,chr12,10116777,10130258
6,HAL,0.005032,Spleen,chr10_80647340_G_GGT_b38,0.337432,0.999514,0.800377,4,chr12,95972662,95996365

,Gene_set,Term,P-value,Adjusted P-value,Old P-value,Old adjusted P-value,Odds Ratio,Combined Score,Genes
0,MSigDB_Hallmark_2020,Allograft Rejection,0.029939,0.898164,0,0,2.521064,8.845403,KRT1;PRF1;CFP;ELANE;CCR2;TLR2;PF4
1,MSigDB_Hallmark_2020,KRAS Signaling Dn,0.137384,0.967208,0,0,2.119818,4.207786,TG;KRT1;MEFV;UPK3B
2,MSigDB_Hallmark_2020,Myogenesis,0.236090,0.967208,0,0,1.558126,2.249223,CFD;MYBPC3;STC2;ITGA7;MYOM2
3,MSigDB_Hallmark_2020,Reactive Oxygen Species Pathway,0.293675,0.967208,0,0,3.230710,3.958534,MPO
4,MSigDB_Hallmark_2020,Bile Acid Metabolism,0.366636,0.967208,0,0,1.615975,1.621445,PIPOX;GNMT

Doing for top 200 gene

,gene_name,p_value,tissue,snp_id,beta,qv,maf,cluster_i,gene_chr,gene_start,gene_end
4,SNHG5,0.002405,Spleen,chr10_80647340_G_GGT_b38,-0.353937,0.999514,0.800377,4,chr6,85660950,85678736
5,RP11-322E11.5,0.003401,Spleen,chr10_80647340_G_GGT_b38,-0.354299,0.999514,0.800377,4,chr18,35443869,35467088
9,SNHG9,0.006665,Spleen,chr10_80647340_G_GGT_b38,-0.318886,0.999514,0.800377,4,chr16,1964959,1965509
11,HAMP,0.007883,Spleen,chr10_80647340_G_GGT_b38,-0.319683,0.999514,0.800377,4,chr19,35280716,35285143
12,AC016739.2,0.008736,Spleen,chr10_80647340_G_GGT_b38,-0.318259,0.999514,0.800377,4,chr2,176200908,176201252

,Gene_set,Term,P-value,Adjusted P-value,Old P-value,Old adjusted P-value,Odds Ratio,Combined Score,Genes
0,MSigDB_Hallmark_2020,Myc Targets V2,0.005651,0.115737,0,0,11.118421,57.549033,NOP2;HSPE1;HSPD1
1,MSigDB_Hallmark_2020,mTORC1 Signaling,0.006808,0.115737,0,0,3.500836,17.467953,STIP1;SDF2L1;HSPA5;MTHFD2;CACYBP;HSPE1;HSPD1
2,MSigDB_Hallmark_2020,Hypoxia,0.019419,0.174088,0,0,2.570502,10.131694,EFNA1;IL6;CSRP2;HSPA5;ACKR3;ALDOB;CP;IER3
3,MSigDB_Hallmark_2020,UV Response Up,0.020481,0.174088,0,0,3.053233,11.871766,STIP1;DNAJB1;IL6;APOM;FKBP4;CXCL2
4,MSigDB_Hallmark_2020,Myc Targets V1,0.030083,0.199799,0,0,5.123077,17.950148,HSPE1;NME1;HSPD1